// Code generated by go-swagger; DO NOT EDIT.

package address_suggest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// AddressSuggestionsUsingGETReader is a Reader for the AddressSuggestionsUsingGET structure.
type AddressSuggestionsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddressSuggestionsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddressSuggestionsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddressSuggestionsUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAddressSuggestionsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddressSuggestionsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAddressSuggestionsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewAddressSuggestionsUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddressSuggestionsUsingGETOK creates a AddressSuggestionsUsingGETOK with default headers values
func NewAddressSuggestionsUsingGETOK() *AddressSuggestionsUsingGETOK {
	return &AddressSuggestionsUsingGETOK{}
}

/*AddressSuggestionsUsingGETOK handles this case with default header values.

Information was found.
*/
type AddressSuggestionsUsingGETOK struct {
	Payload []*models.AddressInfo
}

func (o *AddressSuggestionsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/addressSuggestions/{suggestionType}][%d] addressSuggestionsUsingGETOK  %+v", 200, o.Payload)
}

func (o *AddressSuggestionsUsingGETOK) GetPayload() []*models.AddressInfo {
	return o.Payload
}

func (o *AddressSuggestionsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddressSuggestionsUsingGETBadRequest creates a AddressSuggestionsUsingGETBadRequest with default headers values
func NewAddressSuggestionsUsingGETBadRequest() *AddressSuggestionsUsingGETBadRequest {
	return &AddressSuggestionsUsingGETBadRequest{}
}

/*AddressSuggestionsUsingGETBadRequest handles this case with default header values.

Bad request.
*/
type AddressSuggestionsUsingGETBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *AddressSuggestionsUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/addressSuggestions/{suggestionType}][%d] addressSuggestionsUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *AddressSuggestionsUsingGETBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *AddressSuggestionsUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddressSuggestionsUsingGETUnauthorized creates a AddressSuggestionsUsingGETUnauthorized with default headers values
func NewAddressSuggestionsUsingGETUnauthorized() *AddressSuggestionsUsingGETUnauthorized {
	return &AddressSuggestionsUsingGETUnauthorized{}
}

/*AddressSuggestionsUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type AddressSuggestionsUsingGETUnauthorized struct {
}

func (o *AddressSuggestionsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/addressSuggestions/{suggestionType}][%d] addressSuggestionsUsingGETUnauthorized ", 401)
}

func (o *AddressSuggestionsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddressSuggestionsUsingGETForbidden creates a AddressSuggestionsUsingGETForbidden with default headers values
func NewAddressSuggestionsUsingGETForbidden() *AddressSuggestionsUsingGETForbidden {
	return &AddressSuggestionsUsingGETForbidden{}
}

/*AddressSuggestionsUsingGETForbidden handles this case with default header values.

Forbidden
*/
type AddressSuggestionsUsingGETForbidden struct {
}

func (o *AddressSuggestionsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/addressSuggestions/{suggestionType}][%d] addressSuggestionsUsingGETForbidden ", 403)
}

func (o *AddressSuggestionsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddressSuggestionsUsingGETNotFound creates a AddressSuggestionsUsingGETNotFound with default headers values
func NewAddressSuggestionsUsingGETNotFound() *AddressSuggestionsUsingGETNotFound {
	return &AddressSuggestionsUsingGETNotFound{}
}

/*AddressSuggestionsUsingGETNotFound handles this case with default header values.

Not Found
*/
type AddressSuggestionsUsingGETNotFound struct {
}

func (o *AddressSuggestionsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/addressSuggestions/{suggestionType}][%d] addressSuggestionsUsingGETNotFound ", 404)
}

func (o *AddressSuggestionsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddressSuggestionsUsingGETInternalServerError creates a AddressSuggestionsUsingGETInternalServerError with default headers values
func NewAddressSuggestionsUsingGETInternalServerError() *AddressSuggestionsUsingGETInternalServerError {
	return &AddressSuggestionsUsingGETInternalServerError{}
}

/*AddressSuggestionsUsingGETInternalServerError handles this case with default header values.

Internal Server Error.
*/
type AddressSuggestionsUsingGETInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *AddressSuggestionsUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/addressSuggestions/{suggestionType}][%d] addressSuggestionsUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *AddressSuggestionsUsingGETInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *AddressSuggestionsUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
