// Code generated by go-swagger; DO NOT EDIT.

package address_suggest

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// ExtendedAddressSuggestionsUsingGETReader is a Reader for the ExtendedAddressSuggestionsUsingGET structure.
type ExtendedAddressSuggestionsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtendedAddressSuggestionsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExtendedAddressSuggestionsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExtendedAddressSuggestionsUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewExtendedAddressSuggestionsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewExtendedAddressSuggestionsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewExtendedAddressSuggestionsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewExtendedAddressSuggestionsUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExtendedAddressSuggestionsUsingGETOK creates a ExtendedAddressSuggestionsUsingGETOK with default headers values
func NewExtendedAddressSuggestionsUsingGETOK() *ExtendedAddressSuggestionsUsingGETOK {
	return &ExtendedAddressSuggestionsUsingGETOK{}
}

/*ExtendedAddressSuggestionsUsingGETOK handles this case with default header values.

Information was found.
*/
type ExtendedAddressSuggestionsUsingGETOK struct {
	Payload []*models.AddressInfo
}

func (o *ExtendedAddressSuggestionsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/extended/addressSuggestions/{suggestionType}][%d] extendedAddressSuggestionsUsingGETOK  %+v", 200, o.Payload)
}

func (o *ExtendedAddressSuggestionsUsingGETOK) GetPayload() []*models.AddressInfo {
	return o.Payload
}

func (o *ExtendedAddressSuggestionsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedAddressSuggestionsUsingGETBadRequest creates a ExtendedAddressSuggestionsUsingGETBadRequest with default headers values
func NewExtendedAddressSuggestionsUsingGETBadRequest() *ExtendedAddressSuggestionsUsingGETBadRequest {
	return &ExtendedAddressSuggestionsUsingGETBadRequest{}
}

/*ExtendedAddressSuggestionsUsingGETBadRequest handles this case with default header values.

Bad request.
*/
type ExtendedAddressSuggestionsUsingGETBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedAddressSuggestionsUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/extended/addressSuggestions/{suggestionType}][%d] extendedAddressSuggestionsUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *ExtendedAddressSuggestionsUsingGETBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedAddressSuggestionsUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedAddressSuggestionsUsingGETUnauthorized creates a ExtendedAddressSuggestionsUsingGETUnauthorized with default headers values
func NewExtendedAddressSuggestionsUsingGETUnauthorized() *ExtendedAddressSuggestionsUsingGETUnauthorized {
	return &ExtendedAddressSuggestionsUsingGETUnauthorized{}
}

/*ExtendedAddressSuggestionsUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type ExtendedAddressSuggestionsUsingGETUnauthorized struct {
}

func (o *ExtendedAddressSuggestionsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/extended/addressSuggestions/{suggestionType}][%d] extendedAddressSuggestionsUsingGETUnauthorized ", 401)
}

func (o *ExtendedAddressSuggestionsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExtendedAddressSuggestionsUsingGETForbidden creates a ExtendedAddressSuggestionsUsingGETForbidden with default headers values
func NewExtendedAddressSuggestionsUsingGETForbidden() *ExtendedAddressSuggestionsUsingGETForbidden {
	return &ExtendedAddressSuggestionsUsingGETForbidden{}
}

/*ExtendedAddressSuggestionsUsingGETForbidden handles this case with default header values.

Forbidden
*/
type ExtendedAddressSuggestionsUsingGETForbidden struct {
}

func (o *ExtendedAddressSuggestionsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/extended/addressSuggestions/{suggestionType}][%d] extendedAddressSuggestionsUsingGETForbidden ", 403)
}

func (o *ExtendedAddressSuggestionsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExtendedAddressSuggestionsUsingGETNotFound creates a ExtendedAddressSuggestionsUsingGETNotFound with default headers values
func NewExtendedAddressSuggestionsUsingGETNotFound() *ExtendedAddressSuggestionsUsingGETNotFound {
	return &ExtendedAddressSuggestionsUsingGETNotFound{}
}

/*ExtendedAddressSuggestionsUsingGETNotFound handles this case with default header values.

Not Found
*/
type ExtendedAddressSuggestionsUsingGETNotFound struct {
}

func (o *ExtendedAddressSuggestionsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/extended/addressSuggestions/{suggestionType}][%d] extendedAddressSuggestionsUsingGETNotFound ", 404)
}

func (o *ExtendedAddressSuggestionsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExtendedAddressSuggestionsUsingGETInternalServerError creates a ExtendedAddressSuggestionsUsingGETInternalServerError with default headers values
func NewExtendedAddressSuggestionsUsingGETInternalServerError() *ExtendedAddressSuggestionsUsingGETInternalServerError {
	return &ExtendedAddressSuggestionsUsingGETInternalServerError{}
}

/*ExtendedAddressSuggestionsUsingGETInternalServerError handles this case with default header values.

Internal Server Error.
*/
type ExtendedAddressSuggestionsUsingGETInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedAddressSuggestionsUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSuggest/extended/addressSuggestions/{suggestionType}][%d] extendedAddressSuggestionsUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *ExtendedAddressSuggestionsUsingGETInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedAddressSuggestionsUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
