// Code generated by go-swagger; DO NOT EDIT.

package zipcode_municipality_name_list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams creates a new GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams object
// with the default values initialized.
func NewGetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams() *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams {
	var ()
	return &GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParamsWithTimeout creates a new GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParamsWithTimeout(timeout time.Duration) *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams {
	var ()
	return &GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams{

		timeout: timeout,
	}
}

// NewGetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParamsWithContext creates a new GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParamsWithContext(ctx context.Context) *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams {
	var ()
	return &GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams{

		Context: ctx,
	}
}

// NewGetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParamsWithHTTPClient creates a new GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParamsWithHTTPClient(client *http.Client) *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams {
	var ()
	return &GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams{
		HTTPClient: client,
	}
}

/*GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams contains all the parameters to send to the API endpoint
for the get zipcode municipality name listby onkz and asb using g e t operation typically these are written to a http.Request
*/
type GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams struct {

	/*Asb
	  asb (number from 0 to 9999)

	*/
	Asb *int32
	/*Onkz
	  onkz (number from 30 to 39999)

	*/
	Onkz int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get zipcode municipality name listby onkz and asb using g e t params
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) WithTimeout(timeout time.Duration) *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get zipcode municipality name listby onkz and asb using g e t params
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get zipcode municipality name listby onkz and asb using g e t params
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) WithContext(ctx context.Context) *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get zipcode municipality name listby onkz and asb using g e t params
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get zipcode municipality name listby onkz and asb using g e t params
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) WithHTTPClient(client *http.Client) *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get zipcode municipality name listby onkz and asb using g e t params
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAsb adds the asb to the get zipcode municipality name listby onkz and asb using g e t params
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) WithAsb(asb *int32) *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams {
	o.SetAsb(asb)
	return o
}

// SetAsb adds the asb to the get zipcode municipality name listby onkz and asb using g e t params
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) SetAsb(asb *int32) {
	o.Asb = asb
}

// WithOnkz adds the onkz to the get zipcode municipality name listby onkz and asb using g e t params
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) WithOnkz(onkz int32) *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams {
	o.SetOnkz(onkz)
	return o
}

// SetOnkz adds the onkz to the get zipcode municipality name listby onkz and asb using g e t params
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) SetOnkz(onkz int32) {
	o.Onkz = onkz
}

// WriteToRequest writes these params to a swagger request
func (o *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Asb != nil {

		// query param asb
		var qrAsb int32
		if o.Asb != nil {
			qrAsb = *o.Asb
		}
		qAsb := swag.FormatInt32(qrAsb)
		if qAsb != "" {
			if err := r.SetQueryParam("asb", qAsb); err != nil {
				return err
			}
		}

	}

	// path param onkz
	if err := r.SetPathParam("onkz", swag.FormatInt32(o.Onkz)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
