// Code generated by go-swagger; DO NOT EDIT.

package zipcode_municipality_name_list

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new zipcode municipality name list API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for zipcode municipality name list API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGET(params *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) (*GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGET finds a list of zipcode and city municipality name list by o n k z and a s b

  Returned list of unique pairs of zipcode and cities(municipalityNames). In case of nonvalid onkz/asb controller returns empty list
*/
func (a *Client) GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGET(params *GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams) (*GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getZipcodeMunicipalityNameListbyOnkzAndAsbUsingGET",
		Method:             "GET",
		PathPattern:        "/api/addressLookup/v1/zipcodeMunicipalityNames/getZipcodeMunicipalityNameList/{onkz}",
		ProducesMediaTypes: []string{"*/*"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetZipcodeMunicipalityNameListbyOnkzAndAsbUsingGETOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getZipcodeMunicipalityNameListbyOnkzAndAsbUsingGET: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
