// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddressSuggestion AddressSuggestion
//
// Class representing an address autocompled suggestion.
//
// swagger:model AddressSuggestion
type AddressSuggestion struct {

	// Address suggestion representation
	AddressSuggestion string `json:"addressSuggestion,omitempty"`

	// the district nameof an address
	DistributionAreaName string `json:"distributionAreaName,omitempty"`

	// In KLS system: GEO_LAENGE, Latitude as a decimal value, аormat (999,99999) = max. 9 figures
	GeoLatitude float64 `json:"geoLatitude,omitempty"`

	// In KLS system: GEO_BREITE, Longitude as a decimal value, аormat (999,99999) = max. 9 figures
	GeoLongitude float64 `json:"geoLongitude,omitempty"`

	// the house number of an address
	HouseNumber int32 `json:"houseNumber,omitempty"`

	// the house number supplement of an address
	HouseNumberSupplement string `json:"houseNumberSupplement,omitempty"`

	// the full house number of an address
	HouseQualifier string `json:"houseQualifier,omitempty"`

	// the numeric klsId of this address
	KlsID int64 `json:"klsId,omitempty"`

	// the city of an address
	MunicipalityName string `json:"municipalityName,omitempty"`

	// the street of an address
	StreetName string `json:"streetName,omitempty"`

	// the short street of an address
	StreetNameShort string `json:"streetNameShort,omitempty"`

	// the zipcode of an address
	ZipCode string `json:"zipCode,omitempty"`
}

// Validate validates this address suggestion
func (m *AddressSuggestion) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddressSuggestion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddressSuggestion) UnmarshalBinary(b []byte) error {
	var res AddressSuggestion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
