// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddressSearchCriteria AddressSearchCriteria
//
// Object with criteria for address search
//
// swagger:model AddressSearchCriteria
type AddressSearchCriteria struct {

	// List of klsIds
	KlsIds []string `json:"klsIds"`

	// Maximal number of results to be returned
	MaxResults int32 `json:"maxResults,omitempty"`

	// Onkz value
	Onkz string `json:"onkz,omitempty"`

	// Zipcode value
	ZipCode string `json:"zipCode,omitempty"`
}

// Validate validates this address search criteria
func (m *AddressSearchCriteria) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddressSearchCriteria) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddressSearchCriteria) UnmarshalBinary(b []byte) error {
	var res AddressSearchCriteria
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
