// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AddressInfo AddressInfo
//
// Class representing an address / autocompletion.
//
// swagger:model AddressInfo
type AddressInfo struct {

	// the district nameof an address
	DistributionAreaName string `json:"distributionAreaName,omitempty"`

	// the house number of an address
	HouseNumber int32 `json:"houseNumber,omitempty"`

	// the house number supplement of an address
	HouseNumberSupplement string `json:"houseNumberSupplement,omitempty"`

	// the full house number of an address
	HouseQualifier string `json:"houseQualifier,omitempty"`

	// the numeric klsId of this address
	KlsID int64 `json:"klsId,omitempty"`

	// the city of an address
	MunicipalityName string `json:"municipalityName,omitempty"`

	// the street of an address
	StreetName string `json:"streetName,omitempty"`

	// the short street of an address
	StreetNameShort string `json:"streetNameShort,omitempty"`

	// the zipcode of an address
	ZipCode string `json:"zipCode,omitempty"`
}

// Validate validates this address info
func (m *AddressInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AddressInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AddressInfo) UnmarshalBinary(b []byte) error {
	var res AddressInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
