// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SpecificProblemDetails SpecificProblemDetails
//
// Specific problem details(including fehlerbuildnummer code).
//
// swagger:model SpecificProblemDetails
type SpecificProblemDetails struct {

	// code
	// Required: true
	Code *string `json:"code"`

	// message
	Message string `json:"message,omitempty"`

	// reason
	// Required: true
	Reason *string `json:"reason"`

	// status
	Status int32 `json:"status,omitempty"`
}

// Validate validates this specific problem details
func (m *SpecificProblemDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReason(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SpecificProblemDetails) validateCode(formats strfmt.Registry) error {

	if err := validate.Required("code", "body", m.Code); err != nil {
		return err
	}

	return nil
}

func (m *SpecificProblemDetails) validateReason(formats strfmt.Registry) error {

	if err := validate.Required("reason", "body", m.Reason); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SpecificProblemDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SpecificProblemDetails) UnmarshalBinary(b []byte) error {
	var res SpecificProblemDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
