// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ZipcodeMunicipalityNameDTO ZipcodeMunicipalityNameDTO
//
// Class representing an zipCode/city pair
//
// swagger:model ZipcodeMunicipalityNameDTO
type ZipcodeMunicipalityNameDTO struct {

	// the city of an address
	MunicipalityName string `json:"municipalityName,omitempty"`

	// In KLS system: POSTLEITZAHL, the zipcode of an address
	ZipCode string `json:"zipCode,omitempty"`
}

// Validate validates this zipcode municipality name d t o
func (m *ZipcodeMunicipalityNameDTO) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ZipcodeMunicipalityNameDTO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ZipcodeMunicipalityNameDTO) UnmarshalBinary(b []byte) error {
	var res ZipcodeMunicipalityNameDTO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
