// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// ExtendedGetKlsIDUsingGETReader is a Reader for the ExtendedGetKlsIDUsingGET structure.
type ExtendedGetKlsIDUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtendedGetKlsIDUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExtendedGetKlsIDUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExtendedGetKlsIDUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewExtendedGetKlsIDUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewExtendedGetKlsIDUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewExtendedGetKlsIDUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewExtendedGetKlsIDUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExtendedGetKlsIDUsingGETOK creates a ExtendedGetKlsIDUsingGETOK with default headers values
func NewExtendedGetKlsIDUsingGETOK() *ExtendedGetKlsIDUsingGETOK {
	return &ExtendedGetKlsIDUsingGETOK{}
}

/*ExtendedGetKlsIDUsingGETOK handles this case with default header values.

Information was found.
*/
type ExtendedGetKlsIDUsingGETOK struct {
	Payload int64
}

func (o *ExtendedGetKlsIDUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/getKlsId][%d] extendedGetKlsIdUsingGETOK  %+v", 200, o.Payload)
}

func (o *ExtendedGetKlsIDUsingGETOK) GetPayload() int64 {
	return o.Payload
}

func (o *ExtendedGetKlsIDUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedGetKlsIDUsingGETBadRequest creates a ExtendedGetKlsIDUsingGETBadRequest with default headers values
func NewExtendedGetKlsIDUsingGETBadRequest() *ExtendedGetKlsIDUsingGETBadRequest {
	return &ExtendedGetKlsIDUsingGETBadRequest{}
}

/*ExtendedGetKlsIDUsingGETBadRequest handles this case with default header values.

Bad request.
*/
type ExtendedGetKlsIDUsingGETBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedGetKlsIDUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/getKlsId][%d] extendedGetKlsIdUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *ExtendedGetKlsIDUsingGETBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedGetKlsIDUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedGetKlsIDUsingGETUnauthorized creates a ExtendedGetKlsIDUsingGETUnauthorized with default headers values
func NewExtendedGetKlsIDUsingGETUnauthorized() *ExtendedGetKlsIDUsingGETUnauthorized {
	return &ExtendedGetKlsIDUsingGETUnauthorized{}
}

/*ExtendedGetKlsIDUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type ExtendedGetKlsIDUsingGETUnauthorized struct {
}

func (o *ExtendedGetKlsIDUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/getKlsId][%d] extendedGetKlsIdUsingGETUnauthorized ", 401)
}

func (o *ExtendedGetKlsIDUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExtendedGetKlsIDUsingGETForbidden creates a ExtendedGetKlsIDUsingGETForbidden with default headers values
func NewExtendedGetKlsIDUsingGETForbidden() *ExtendedGetKlsIDUsingGETForbidden {
	return &ExtendedGetKlsIDUsingGETForbidden{}
}

/*ExtendedGetKlsIDUsingGETForbidden handles this case with default header values.

Forbidden
*/
type ExtendedGetKlsIDUsingGETForbidden struct {
}

func (o *ExtendedGetKlsIDUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/getKlsId][%d] extendedGetKlsIdUsingGETForbidden ", 403)
}

func (o *ExtendedGetKlsIDUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExtendedGetKlsIDUsingGETNotFound creates a ExtendedGetKlsIDUsingGETNotFound with default headers values
func NewExtendedGetKlsIDUsingGETNotFound() *ExtendedGetKlsIDUsingGETNotFound {
	return &ExtendedGetKlsIDUsingGETNotFound{}
}

/*ExtendedGetKlsIDUsingGETNotFound handles this case with default header values.

KlsId was not found for specified address.
*/
type ExtendedGetKlsIDUsingGETNotFound struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedGetKlsIDUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/getKlsId][%d] extendedGetKlsIdUsingGETNotFound  %+v", 404, o.Payload)
}

func (o *ExtendedGetKlsIDUsingGETNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedGetKlsIDUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedGetKlsIDUsingGETInternalServerError creates a ExtendedGetKlsIDUsingGETInternalServerError with default headers values
func NewExtendedGetKlsIDUsingGETInternalServerError() *ExtendedGetKlsIDUsingGETInternalServerError {
	return &ExtendedGetKlsIDUsingGETInternalServerError{}
}

/*ExtendedGetKlsIDUsingGETInternalServerError handles this case with default header values.

Internal Server Error.
*/
type ExtendedGetKlsIDUsingGETInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedGetKlsIDUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/getKlsId][%d] extendedGetKlsIdUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *ExtendedGetKlsIDUsingGETInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedGetKlsIDUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
