// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewExtendedResolveAddressInfoUsingGETParams creates a new ExtendedResolveAddressInfoUsingGETParams object
// with the default values initialized.
func NewExtendedResolveAddressInfoUsingGETParams() *ExtendedResolveAddressInfoUsingGETParams {
	var ()
	return &ExtendedResolveAddressInfoUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewExtendedResolveAddressInfoUsingGETParamsWithTimeout creates a new ExtendedResolveAddressInfoUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewExtendedResolveAddressInfoUsingGETParamsWithTimeout(timeout time.Duration) *ExtendedResolveAddressInfoUsingGETParams {
	var ()
	return &ExtendedResolveAddressInfoUsingGETParams{

		timeout: timeout,
	}
}

// NewExtendedResolveAddressInfoUsingGETParamsWithContext creates a new ExtendedResolveAddressInfoUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewExtendedResolveAddressInfoUsingGETParamsWithContext(ctx context.Context) *ExtendedResolveAddressInfoUsingGETParams {
	var ()
	return &ExtendedResolveAddressInfoUsingGETParams{

		Context: ctx,
	}
}

// NewExtendedResolveAddressInfoUsingGETParamsWithHTTPClient creates a new ExtendedResolveAddressInfoUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewExtendedResolveAddressInfoUsingGETParamsWithHTTPClient(client *http.Client) *ExtendedResolveAddressInfoUsingGETParams {
	var ()
	return &ExtendedResolveAddressInfoUsingGETParams{
		HTTPClient: client,
	}
}

/*ExtendedResolveAddressInfoUsingGETParams contains all the parameters to send to the API endpoint
for the extended resolve address info using g e t operation typically these are written to a http.Request
*/
type ExtendedResolveAddressInfoUsingGETParams struct {

	/*HouseNumber
	  House number

	*/
	HouseNumber int32
	/*HouseNumberSupplement
	  House number supplement

	*/
	HouseNumberSupplement *string
	/*MunicipalityName
	  Municipality (city) name

	*/
	MunicipalityName string
	/*StreetName
	  Street name

	*/
	StreetName string
	/*ZipCode
	  Zip code

	*/
	ZipCode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) WithTimeout(timeout time.Duration) *ExtendedResolveAddressInfoUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) WithContext(ctx context.Context) *ExtendedResolveAddressInfoUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) WithHTTPClient(client *http.Client) *ExtendedResolveAddressInfoUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHouseNumber adds the houseNumber to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) WithHouseNumber(houseNumber int32) *ExtendedResolveAddressInfoUsingGETParams {
	o.SetHouseNumber(houseNumber)
	return o
}

// SetHouseNumber adds the houseNumber to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) SetHouseNumber(houseNumber int32) {
	o.HouseNumber = houseNumber
}

// WithHouseNumberSupplement adds the houseNumberSupplement to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) WithHouseNumberSupplement(houseNumberSupplement *string) *ExtendedResolveAddressInfoUsingGETParams {
	o.SetHouseNumberSupplement(houseNumberSupplement)
	return o
}

// SetHouseNumberSupplement adds the houseNumberSupplement to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) SetHouseNumberSupplement(houseNumberSupplement *string) {
	o.HouseNumberSupplement = houseNumberSupplement
}

// WithMunicipalityName adds the municipalityName to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) WithMunicipalityName(municipalityName string) *ExtendedResolveAddressInfoUsingGETParams {
	o.SetMunicipalityName(municipalityName)
	return o
}

// SetMunicipalityName adds the municipalityName to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) SetMunicipalityName(municipalityName string) {
	o.MunicipalityName = municipalityName
}

// WithStreetName adds the streetName to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) WithStreetName(streetName string) *ExtendedResolveAddressInfoUsingGETParams {
	o.SetStreetName(streetName)
	return o
}

// SetStreetName adds the streetName to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) SetStreetName(streetName string) {
	o.StreetName = streetName
}

// WithZipCode adds the zipCode to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) WithZipCode(zipCode string) *ExtendedResolveAddressInfoUsingGETParams {
	o.SetZipCode(zipCode)
	return o
}

// SetZipCode adds the zipCode to the extended resolve address info using g e t params
func (o *ExtendedResolveAddressInfoUsingGETParams) SetZipCode(zipCode string) {
	o.ZipCode = zipCode
}

// WriteToRequest writes these params to a swagger request
func (o *ExtendedResolveAddressInfoUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param houseNumber
	qrHouseNumber := o.HouseNumber
	qHouseNumber := swag.FormatInt32(qrHouseNumber)
	if qHouseNumber != "" {
		if err := r.SetQueryParam("houseNumber", qHouseNumber); err != nil {
			return err
		}
	}

	if o.HouseNumberSupplement != nil {

		// query param houseNumberSupplement
		var qrHouseNumberSupplement string
		if o.HouseNumberSupplement != nil {
			qrHouseNumberSupplement = *o.HouseNumberSupplement
		}
		qHouseNumberSupplement := qrHouseNumberSupplement
		if qHouseNumberSupplement != "" {
			if err := r.SetQueryParam("houseNumberSupplement", qHouseNumberSupplement); err != nil {
				return err
			}
		}

	}

	// query param municipalityName
	qrMunicipalityName := o.MunicipalityName
	qMunicipalityName := qrMunicipalityName
	if qMunicipalityName != "" {
		if err := r.SetQueryParam("municipalityName", qMunicipalityName); err != nil {
			return err
		}
	}

	// query param streetName
	qrStreetName := o.StreetName
	qStreetName := qrStreetName
	if qStreetName != "" {
		if err := r.SetQueryParam("streetName", qStreetName); err != nil {
			return err
		}
	}

	// query param zipCode
	qrZipCode := o.ZipCode
	qZipCode := qrZipCode
	if qZipCode != "" {
		if err := r.SetQueryParam("zipCode", qZipCode); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
