// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// ExtendedResolveAddressInfoUsingGETReader is a Reader for the ExtendedResolveAddressInfoUsingGET structure.
type ExtendedResolveAddressInfoUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtendedResolveAddressInfoUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExtendedResolveAddressInfoUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExtendedResolveAddressInfoUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewExtendedResolveAddressInfoUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewExtendedResolveAddressInfoUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewExtendedResolveAddressInfoUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewExtendedResolveAddressInfoUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExtendedResolveAddressInfoUsingGETOK creates a ExtendedResolveAddressInfoUsingGETOK with default headers values
func NewExtendedResolveAddressInfoUsingGETOK() *ExtendedResolveAddressInfoUsingGETOK {
	return &ExtendedResolveAddressInfoUsingGETOK{}
}

/*ExtendedResolveAddressInfoUsingGETOK handles this case with default header values.

Information was found.
*/
type ExtendedResolveAddressInfoUsingGETOK struct {
	Payload *models.AddressInfo
}

func (o *ExtendedResolveAddressInfoUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/resolveAddressInfo][%d] extendedResolveAddressInfoUsingGETOK  %+v", 200, o.Payload)
}

func (o *ExtendedResolveAddressInfoUsingGETOK) GetPayload() *models.AddressInfo {
	return o.Payload
}

func (o *ExtendedResolveAddressInfoUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AddressInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedResolveAddressInfoUsingGETBadRequest creates a ExtendedResolveAddressInfoUsingGETBadRequest with default headers values
func NewExtendedResolveAddressInfoUsingGETBadRequest() *ExtendedResolveAddressInfoUsingGETBadRequest {
	return &ExtendedResolveAddressInfoUsingGETBadRequest{}
}

/*ExtendedResolveAddressInfoUsingGETBadRequest handles this case with default header values.

Bad request.
*/
type ExtendedResolveAddressInfoUsingGETBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedResolveAddressInfoUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/resolveAddressInfo][%d] extendedResolveAddressInfoUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *ExtendedResolveAddressInfoUsingGETBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedResolveAddressInfoUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedResolveAddressInfoUsingGETUnauthorized creates a ExtendedResolveAddressInfoUsingGETUnauthorized with default headers values
func NewExtendedResolveAddressInfoUsingGETUnauthorized() *ExtendedResolveAddressInfoUsingGETUnauthorized {
	return &ExtendedResolveAddressInfoUsingGETUnauthorized{}
}

/*ExtendedResolveAddressInfoUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type ExtendedResolveAddressInfoUsingGETUnauthorized struct {
}

func (o *ExtendedResolveAddressInfoUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/resolveAddressInfo][%d] extendedResolveAddressInfoUsingGETUnauthorized ", 401)
}

func (o *ExtendedResolveAddressInfoUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExtendedResolveAddressInfoUsingGETForbidden creates a ExtendedResolveAddressInfoUsingGETForbidden with default headers values
func NewExtendedResolveAddressInfoUsingGETForbidden() *ExtendedResolveAddressInfoUsingGETForbidden {
	return &ExtendedResolveAddressInfoUsingGETForbidden{}
}

/*ExtendedResolveAddressInfoUsingGETForbidden handles this case with default header values.

Forbidden
*/
type ExtendedResolveAddressInfoUsingGETForbidden struct {
}

func (o *ExtendedResolveAddressInfoUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/resolveAddressInfo][%d] extendedResolveAddressInfoUsingGETForbidden ", 403)
}

func (o *ExtendedResolveAddressInfoUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExtendedResolveAddressInfoUsingGETNotFound creates a ExtendedResolveAddressInfoUsingGETNotFound with default headers values
func NewExtendedResolveAddressInfoUsingGETNotFound() *ExtendedResolveAddressInfoUsingGETNotFound {
	return &ExtendedResolveAddressInfoUsingGETNotFound{}
}

/*ExtendedResolveAddressInfoUsingGETNotFound handles this case with default header values.

KlsId was not found for specified address.
*/
type ExtendedResolveAddressInfoUsingGETNotFound struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedResolveAddressInfoUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/resolveAddressInfo][%d] extendedResolveAddressInfoUsingGETNotFound  %+v", 404, o.Payload)
}

func (o *ExtendedResolveAddressInfoUsingGETNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedResolveAddressInfoUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedResolveAddressInfoUsingGETInternalServerError creates a ExtendedResolveAddressInfoUsingGETInternalServerError with default headers values
func NewExtendedResolveAddressInfoUsingGETInternalServerError() *ExtendedResolveAddressInfoUsingGETInternalServerError {
	return &ExtendedResolveAddressInfoUsingGETInternalServerError{}
}

/*ExtendedResolveAddressInfoUsingGETInternalServerError handles this case with default header values.

Internal Server Error.
*/
type ExtendedResolveAddressInfoUsingGETInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedResolveAddressInfoUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/extended/resolveAddressInfo][%d] extendedResolveAddressInfoUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *ExtendedResolveAddressInfoUsingGETInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedResolveAddressInfoUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
