// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// ExtendedResolveFullAddressInfoUsingGETReader is a Reader for the ExtendedResolveFullAddressInfoUsingGET structure.
type ExtendedResolveFullAddressInfoUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExtendedResolveFullAddressInfoUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewExtendedResolveFullAddressInfoUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExtendedResolveFullAddressInfoUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewExtendedResolveFullAddressInfoUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewExtendedResolveFullAddressInfoUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewExtendedResolveFullAddressInfoUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewExtendedResolveFullAddressInfoUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExtendedResolveFullAddressInfoUsingGETOK creates a ExtendedResolveFullAddressInfoUsingGETOK with default headers values
func NewExtendedResolveFullAddressInfoUsingGETOK() *ExtendedResolveFullAddressInfoUsingGETOK {
	return &ExtendedResolveFullAddressInfoUsingGETOK{}
}

/*ExtendedResolveFullAddressInfoUsingGETOK handles this case with default header values.

Information was found.
*/
type ExtendedResolveFullAddressInfoUsingGETOK struct {
	Payload *models.FullAddressInfo
}

func (o *ExtendedResolveFullAddressInfoUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /giga-areas-location/v1/lookup/addressSearch/extended/resolveFullAddressInfo][%d] extendedResolveFullAddressInfoUsingGETOK  %+v", 200, o.Payload)
}

func (o *ExtendedResolveFullAddressInfoUsingGETOK) GetPayload() *models.FullAddressInfo {
	return o.Payload
}

func (o *ExtendedResolveFullAddressInfoUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FullAddressInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedResolveFullAddressInfoUsingGETBadRequest creates a ExtendedResolveFullAddressInfoUsingGETBadRequest with default headers values
func NewExtendedResolveFullAddressInfoUsingGETBadRequest() *ExtendedResolveFullAddressInfoUsingGETBadRequest {
	return &ExtendedResolveFullAddressInfoUsingGETBadRequest{}
}

/*ExtendedResolveFullAddressInfoUsingGETBadRequest handles this case with default header values.

Bad request.
*/
type ExtendedResolveFullAddressInfoUsingGETBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedResolveFullAddressInfoUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /giga-areas-location/v1/lookup/addressSearch/extended/resolveFullAddressInfo][%d] extendedResolveFullAddressInfoUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *ExtendedResolveFullAddressInfoUsingGETBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedResolveFullAddressInfoUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedResolveFullAddressInfoUsingGETUnauthorized creates a ExtendedResolveFullAddressInfoUsingGETUnauthorized with default headers values
func NewExtendedResolveFullAddressInfoUsingGETUnauthorized() *ExtendedResolveFullAddressInfoUsingGETUnauthorized {
	return &ExtendedResolveFullAddressInfoUsingGETUnauthorized{}
}

/*ExtendedResolveFullAddressInfoUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type ExtendedResolveFullAddressInfoUsingGETUnauthorized struct {
}

func (o *ExtendedResolveFullAddressInfoUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /giga-areas-location/v1/lookup/addressSearch/extended/resolveFullAddressInfo][%d] extendedResolveFullAddressInfoUsingGETUnauthorized ", 401)
}

func (o *ExtendedResolveFullAddressInfoUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExtendedResolveFullAddressInfoUsingGETForbidden creates a ExtendedResolveFullAddressInfoUsingGETForbidden with default headers values
func NewExtendedResolveFullAddressInfoUsingGETForbidden() *ExtendedResolveFullAddressInfoUsingGETForbidden {
	return &ExtendedResolveFullAddressInfoUsingGETForbidden{}
}

/*ExtendedResolveFullAddressInfoUsingGETForbidden handles this case with default header values.

Forbidden
*/
type ExtendedResolveFullAddressInfoUsingGETForbidden struct {
}

func (o *ExtendedResolveFullAddressInfoUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /giga-areas-location/v1/lookup/addressSearch/extended/resolveFullAddressInfo][%d] extendedResolveFullAddressInfoUsingGETForbidden ", 403)
}

func (o *ExtendedResolveFullAddressInfoUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExtendedResolveFullAddressInfoUsingGETNotFound creates a ExtendedResolveFullAddressInfoUsingGETNotFound with default headers values
func NewExtendedResolveFullAddressInfoUsingGETNotFound() *ExtendedResolveFullAddressInfoUsingGETNotFound {
	return &ExtendedResolveFullAddressInfoUsingGETNotFound{}
}

/*ExtendedResolveFullAddressInfoUsingGETNotFound handles this case with default header values.

KlsId was not found for specified address.
*/
type ExtendedResolveFullAddressInfoUsingGETNotFound struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedResolveFullAddressInfoUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /giga-areas-location/v1/lookup/addressSearch/extended/resolveFullAddressInfo][%d] extendedResolveFullAddressInfoUsingGETNotFound  %+v", 404, o.Payload)
}

func (o *ExtendedResolveFullAddressInfoUsingGETNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedResolveFullAddressInfoUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExtendedResolveFullAddressInfoUsingGETInternalServerError creates a ExtendedResolveFullAddressInfoUsingGETInternalServerError with default headers values
func NewExtendedResolveFullAddressInfoUsingGETInternalServerError() *ExtendedResolveFullAddressInfoUsingGETInternalServerError {
	return &ExtendedResolveFullAddressInfoUsingGETInternalServerError{}
}

/*ExtendedResolveFullAddressInfoUsingGETInternalServerError handles this case with default header values.

Internal Server Error.
*/
type ExtendedResolveFullAddressInfoUsingGETInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *ExtendedResolveFullAddressInfoUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /giga-areas-location/v1/lookup/addressSearch/extended/resolveFullAddressInfo][%d] extendedResolveFullAddressInfoUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *ExtendedResolveFullAddressInfoUsingGETInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *ExtendedResolveFullAddressInfoUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
