// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// GetFullAddressInfoByKlsIDUsingGETReader is a Reader for the GetFullAddressInfoByKlsIDUsingGET structure.
type GetFullAddressInfoByKlsIDUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetFullAddressInfoByKlsIDUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetFullAddressInfoByKlsIDUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetFullAddressInfoByKlsIDUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetFullAddressInfoByKlsIDUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetFullAddressInfoByKlsIDUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetFullAddressInfoByKlsIDUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetFullAddressInfoByKlsIDUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetFullAddressInfoByKlsIDUsingGETOK creates a GetFullAddressInfoByKlsIDUsingGETOK with default headers values
func NewGetFullAddressInfoByKlsIDUsingGETOK() *GetFullAddressInfoByKlsIDUsingGETOK {
	return &GetFullAddressInfoByKlsIDUsingGETOK{}
}

/*GetFullAddressInfoByKlsIDUsingGETOK handles this case with default header values.

Information was found.
*/
type GetFullAddressInfoByKlsIDUsingGETOK struct {
	Payload *models.FullAddressInfo
}

func (o *GetFullAddressInfoByKlsIDUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getFullAddressInfo/{klsId}][%d] getFullAddressInfoByKlsIdUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetFullAddressInfoByKlsIDUsingGETOK) GetPayload() *models.FullAddressInfo {
	return o.Payload
}

func (o *GetFullAddressInfoByKlsIDUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FullAddressInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFullAddressInfoByKlsIDUsingGETBadRequest creates a GetFullAddressInfoByKlsIDUsingGETBadRequest with default headers values
func NewGetFullAddressInfoByKlsIDUsingGETBadRequest() *GetFullAddressInfoByKlsIDUsingGETBadRequest {
	return &GetFullAddressInfoByKlsIDUsingGETBadRequest{}
}

/*GetFullAddressInfoByKlsIDUsingGETBadRequest handles this case with default header values.

Bad request.
*/
type GetFullAddressInfoByKlsIDUsingGETBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *GetFullAddressInfoByKlsIDUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getFullAddressInfo/{klsId}][%d] getFullAddressInfoByKlsIdUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *GetFullAddressInfoByKlsIDUsingGETBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetFullAddressInfoByKlsIDUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFullAddressInfoByKlsIDUsingGETUnauthorized creates a GetFullAddressInfoByKlsIDUsingGETUnauthorized with default headers values
func NewGetFullAddressInfoByKlsIDUsingGETUnauthorized() *GetFullAddressInfoByKlsIDUsingGETUnauthorized {
	return &GetFullAddressInfoByKlsIDUsingGETUnauthorized{}
}

/*GetFullAddressInfoByKlsIDUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetFullAddressInfoByKlsIDUsingGETUnauthorized struct {
}

func (o *GetFullAddressInfoByKlsIDUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getFullAddressInfo/{klsId}][%d] getFullAddressInfoByKlsIdUsingGETUnauthorized ", 401)
}

func (o *GetFullAddressInfoByKlsIDUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFullAddressInfoByKlsIDUsingGETForbidden creates a GetFullAddressInfoByKlsIDUsingGETForbidden with default headers values
func NewGetFullAddressInfoByKlsIDUsingGETForbidden() *GetFullAddressInfoByKlsIDUsingGETForbidden {
	return &GetFullAddressInfoByKlsIDUsingGETForbidden{}
}

/*GetFullAddressInfoByKlsIDUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetFullAddressInfoByKlsIDUsingGETForbidden struct {
}

func (o *GetFullAddressInfoByKlsIDUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getFullAddressInfo/{klsId}][%d] getFullAddressInfoByKlsIdUsingGETForbidden ", 403)
}

func (o *GetFullAddressInfoByKlsIDUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetFullAddressInfoByKlsIDUsingGETNotFound creates a GetFullAddressInfoByKlsIDUsingGETNotFound with default headers values
func NewGetFullAddressInfoByKlsIDUsingGETNotFound() *GetFullAddressInfoByKlsIDUsingGETNotFound {
	return &GetFullAddressInfoByKlsIDUsingGETNotFound{}
}

/*GetFullAddressInfoByKlsIDUsingGETNotFound handles this case with default header values.

Address information was not found.
*/
type GetFullAddressInfoByKlsIDUsingGETNotFound struct {
	Payload *models.ProblemDetails
}

func (o *GetFullAddressInfoByKlsIDUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getFullAddressInfo/{klsId}][%d] getFullAddressInfoByKlsIdUsingGETNotFound  %+v", 404, o.Payload)
}

func (o *GetFullAddressInfoByKlsIDUsingGETNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetFullAddressInfoByKlsIDUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetFullAddressInfoByKlsIDUsingGETInternalServerError creates a GetFullAddressInfoByKlsIDUsingGETInternalServerError with default headers values
func NewGetFullAddressInfoByKlsIDUsingGETInternalServerError() *GetFullAddressInfoByKlsIDUsingGETInternalServerError {
	return &GetFullAddressInfoByKlsIDUsingGETInternalServerError{}
}

/*GetFullAddressInfoByKlsIDUsingGETInternalServerError handles this case with default header values.

Internal Server Error.
*/
type GetFullAddressInfoByKlsIDUsingGETInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *GetFullAddressInfoByKlsIDUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getFullAddressInfo/{klsId}][%d] getFullAddressInfoByKlsIdUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *GetFullAddressInfoByKlsIDUsingGETInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetFullAddressInfoByKlsIDUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
