// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAddressInfoByKlsIDUsingGETParams creates a new GetAddressInfoByKlsIDUsingGETParams object
// with the default values initialized.
func NewGetAddressInfoByKlsIDUsingGETParams() *GetAddressInfoByKlsIDUsingGETParams {
	var ()
	return &GetAddressInfoByKlsIDUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAddressInfoByKlsIDUsingGETParamsWithTimeout creates a new GetAddressInfoByKlsIDUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAddressInfoByKlsIDUsingGETParamsWithTimeout(timeout time.Duration) *GetAddressInfoByKlsIDUsingGETParams {
	var ()
	return &GetAddressInfoByKlsIDUsingGETParams{

		timeout: timeout,
	}
}

// NewGetAddressInfoByKlsIDUsingGETParamsWithContext creates a new GetAddressInfoByKlsIDUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAddressInfoByKlsIDUsingGETParamsWithContext(ctx context.Context) *GetAddressInfoByKlsIDUsingGETParams {
	var ()
	return &GetAddressInfoByKlsIDUsingGETParams{

		Context: ctx,
	}
}

// NewGetAddressInfoByKlsIDUsingGETParamsWithHTTPClient creates a new GetAddressInfoByKlsIDUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAddressInfoByKlsIDUsingGETParamsWithHTTPClient(client *http.Client) *GetAddressInfoByKlsIDUsingGETParams {
	var ()
	return &GetAddressInfoByKlsIDUsingGETParams{
		HTTPClient: client,
	}
}

/*GetAddressInfoByKlsIDUsingGETParams contains all the parameters to send to the API endpoint
for the get address info by kls Id using g e t operation typically these are written to a http.Request
*/
type GetAddressInfoByKlsIDUsingGETParams struct {

	/*KlsID
	  KlsId of the address

	*/
	KlsID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get address info by kls Id using g e t params
func (o *GetAddressInfoByKlsIDUsingGETParams) WithTimeout(timeout time.Duration) *GetAddressInfoByKlsIDUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get address info by kls Id using g e t params
func (o *GetAddressInfoByKlsIDUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get address info by kls Id using g e t params
func (o *GetAddressInfoByKlsIDUsingGETParams) WithContext(ctx context.Context) *GetAddressInfoByKlsIDUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get address info by kls Id using g e t params
func (o *GetAddressInfoByKlsIDUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get address info by kls Id using g e t params
func (o *GetAddressInfoByKlsIDUsingGETParams) WithHTTPClient(client *http.Client) *GetAddressInfoByKlsIDUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get address info by kls Id using g e t params
func (o *GetAddressInfoByKlsIDUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKlsID adds the klsID to the get address info by kls Id using g e t params
func (o *GetAddressInfoByKlsIDUsingGETParams) WithKlsID(klsID int64) *GetAddressInfoByKlsIDUsingGETParams {
	o.SetKlsID(klsID)
	return o
}

// SetKlsID adds the klsId to the get address info by kls Id using g e t params
func (o *GetAddressInfoByKlsIDUsingGETParams) SetKlsID(klsID int64) {
	o.KlsID = klsID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAddressInfoByKlsIDUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param klsId
	if err := r.SetPathParam("klsId", swag.FormatInt64(o.KlsID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
