// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetKlsIDUsingGETParams creates a new GetKlsIDUsingGETParams object
// with the default values initialized.
func NewGetKlsIDUsingGETParams() *GetKlsIDUsingGETParams {
	var ()
	return &GetKlsIDUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetKlsIDUsingGETParamsWithTimeout creates a new GetKlsIDUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetKlsIDUsingGETParamsWithTimeout(timeout time.Duration) *GetKlsIDUsingGETParams {
	var ()
	return &GetKlsIDUsingGETParams{

		timeout: timeout,
	}
}

// NewGetKlsIDUsingGETParamsWithContext creates a new GetKlsIDUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetKlsIDUsingGETParamsWithContext(ctx context.Context) *GetKlsIDUsingGETParams {
	var ()
	return &GetKlsIDUsingGETParams{

		Context: ctx,
	}
}

// NewGetKlsIDUsingGETParamsWithHTTPClient creates a new GetKlsIDUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetKlsIDUsingGETParamsWithHTTPClient(client *http.Client) *GetKlsIDUsingGETParams {
	var ()
	return &GetKlsIDUsingGETParams{
		HTTPClient: client,
	}
}

/*GetKlsIDUsingGETParams contains all the parameters to send to the API endpoint
for the get kls Id using g e t operation typically these are written to a http.Request
*/
type GetKlsIDUsingGETParams struct {

	/*HouseQualifier
	  Full house number

	*/
	HouseQualifier string
	/*MunicipalityName
	  Municipality (city) name

	*/
	MunicipalityName string
	/*StreetName
	  Street name

	*/
	StreetName string
	/*ZipCode
	  Zip code

	*/
	ZipCode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) WithTimeout(timeout time.Duration) *GetKlsIDUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) WithContext(ctx context.Context) *GetKlsIDUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) WithHTTPClient(client *http.Client) *GetKlsIDUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHouseQualifier adds the houseQualifier to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) WithHouseQualifier(houseQualifier string) *GetKlsIDUsingGETParams {
	o.SetHouseQualifier(houseQualifier)
	return o
}

// SetHouseQualifier adds the houseQualifier to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) SetHouseQualifier(houseQualifier string) {
	o.HouseQualifier = houseQualifier
}

// WithMunicipalityName adds the municipalityName to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) WithMunicipalityName(municipalityName string) *GetKlsIDUsingGETParams {
	o.SetMunicipalityName(municipalityName)
	return o
}

// SetMunicipalityName adds the municipalityName to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) SetMunicipalityName(municipalityName string) {
	o.MunicipalityName = municipalityName
}

// WithStreetName adds the streetName to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) WithStreetName(streetName string) *GetKlsIDUsingGETParams {
	o.SetStreetName(streetName)
	return o
}

// SetStreetName adds the streetName to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) SetStreetName(streetName string) {
	o.StreetName = streetName
}

// WithZipCode adds the zipCode to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) WithZipCode(zipCode string) *GetKlsIDUsingGETParams {
	o.SetZipCode(zipCode)
	return o
}

// SetZipCode adds the zipCode to the get kls Id using g e t params
func (o *GetKlsIDUsingGETParams) SetZipCode(zipCode string) {
	o.ZipCode = zipCode
}

// WriteToRequest writes these params to a swagger request
func (o *GetKlsIDUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param houseQualifier
	qrHouseQualifier := o.HouseQualifier
	qHouseQualifier := qrHouseQualifier
	if qHouseQualifier != "" {
		if err := r.SetQueryParam("houseQualifier", qHouseQualifier); err != nil {
			return err
		}
	}

	// query param municipalityName
	qrMunicipalityName := o.MunicipalityName
	qMunicipalityName := qrMunicipalityName
	if qMunicipalityName != "" {
		if err := r.SetQueryParam("municipalityName", qMunicipalityName); err != nil {
			return err
		}
	}

	// query param streetName
	qrStreetName := o.StreetName
	qStreetName := qrStreetName
	if qStreetName != "" {
		if err := r.SetQueryParam("streetName", qStreetName); err != nil {
			return err
		}
	}

	// query param zipCode
	qrZipCode := o.ZipCode
	qZipCode := qrZipCode
	if qZipCode != "" {
		if err := r.SetQueryParam("zipCode", qZipCode); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
