// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// GetAddressInfoByKlsIDUsingGETReader is a Reader for the GetAddressInfoByKlsIDUsingGET structure.
type GetAddressInfoByKlsIDUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAddressInfoByKlsIDUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAddressInfoByKlsIDUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAddressInfoByKlsIDUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAddressInfoByKlsIDUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAddressInfoByKlsIDUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAddressInfoByKlsIDUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAddressInfoByKlsIDUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAddressInfoByKlsIDUsingGETOK creates a GetAddressInfoByKlsIDUsingGETOK with default headers values
func NewGetAddressInfoByKlsIDUsingGETOK() *GetAddressInfoByKlsIDUsingGETOK {
	return &GetAddressInfoByKlsIDUsingGETOK{}
}

/*GetAddressInfoByKlsIDUsingGETOK handles this case with default header values.

Information was found.
*/
type GetAddressInfoByKlsIDUsingGETOK struct {
	Payload *models.AddressInfo
}

func (o *GetAddressInfoByKlsIDUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getAddressInfo/{klsId}][%d] getAddressInfoByKlsIdUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetAddressInfoByKlsIDUsingGETOK) GetPayload() *models.AddressInfo {
	return o.Payload
}

func (o *GetAddressInfoByKlsIDUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AddressInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAddressInfoByKlsIDUsingGETBadRequest creates a GetAddressInfoByKlsIDUsingGETBadRequest with default headers values
func NewGetAddressInfoByKlsIDUsingGETBadRequest() *GetAddressInfoByKlsIDUsingGETBadRequest {
	return &GetAddressInfoByKlsIDUsingGETBadRequest{}
}

/*GetAddressInfoByKlsIDUsingGETBadRequest handles this case with default header values.

Bad request.
*/
type GetAddressInfoByKlsIDUsingGETBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *GetAddressInfoByKlsIDUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getAddressInfo/{klsId}][%d] getAddressInfoByKlsIdUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *GetAddressInfoByKlsIDUsingGETBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetAddressInfoByKlsIDUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAddressInfoByKlsIDUsingGETUnauthorized creates a GetAddressInfoByKlsIDUsingGETUnauthorized with default headers values
func NewGetAddressInfoByKlsIDUsingGETUnauthorized() *GetAddressInfoByKlsIDUsingGETUnauthorized {
	return &GetAddressInfoByKlsIDUsingGETUnauthorized{}
}

/*GetAddressInfoByKlsIDUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAddressInfoByKlsIDUsingGETUnauthorized struct {
}

func (o *GetAddressInfoByKlsIDUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getAddressInfo/{klsId}][%d] getAddressInfoByKlsIdUsingGETUnauthorized ", 401)
}

func (o *GetAddressInfoByKlsIDUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAddressInfoByKlsIDUsingGETForbidden creates a GetAddressInfoByKlsIDUsingGETForbidden with default headers values
func NewGetAddressInfoByKlsIDUsingGETForbidden() *GetAddressInfoByKlsIDUsingGETForbidden {
	return &GetAddressInfoByKlsIDUsingGETForbidden{}
}

/*GetAddressInfoByKlsIDUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetAddressInfoByKlsIDUsingGETForbidden struct {
}

func (o *GetAddressInfoByKlsIDUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getAddressInfo/{klsId}][%d] getAddressInfoByKlsIdUsingGETForbidden ", 403)
}

func (o *GetAddressInfoByKlsIDUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAddressInfoByKlsIDUsingGETNotFound creates a GetAddressInfoByKlsIDUsingGETNotFound with default headers values
func NewGetAddressInfoByKlsIDUsingGETNotFound() *GetAddressInfoByKlsIDUsingGETNotFound {
	return &GetAddressInfoByKlsIDUsingGETNotFound{}
}

/*GetAddressInfoByKlsIDUsingGETNotFound handles this case with default header values.

Address information was not found.
*/
type GetAddressInfoByKlsIDUsingGETNotFound struct {
	Payload *models.ProblemDetails
}

func (o *GetAddressInfoByKlsIDUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getAddressInfo/{klsId}][%d] getAddressInfoByKlsIdUsingGETNotFound  %+v", 404, o.Payload)
}

func (o *GetAddressInfoByKlsIDUsingGETNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetAddressInfoByKlsIDUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAddressInfoByKlsIDUsingGETInternalServerError creates a GetAddressInfoByKlsIDUsingGETInternalServerError with default headers values
func NewGetAddressInfoByKlsIDUsingGETInternalServerError() *GetAddressInfoByKlsIDUsingGETInternalServerError {
	return &GetAddressInfoByKlsIDUsingGETInternalServerError{}
}

/*GetAddressInfoByKlsIDUsingGETInternalServerError handles this case with default header values.

Internal Server Error.
*/
type GetAddressInfoByKlsIDUsingGETInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *GetAddressInfoByKlsIDUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v1/addressSearch/getAddressInfo/{klsId}][%d] getAddressInfoByKlsIdUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAddressInfoByKlsIDUsingGETInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetAddressInfoByKlsIDUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
