// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetFullAddressInfoByKlsIDUsingGETParams creates a new GetFullAddressInfoByKlsIDUsingGETParams object
// with the default values initialized.
func NewGetFullAddressInfoByKlsIDUsingGETParams() *GetFullAddressInfoByKlsIDUsingGETParams {
	var ()
	return &GetFullAddressInfoByKlsIDUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetFullAddressInfoByKlsIDUsingGETParamsWithTimeout creates a new GetFullAddressInfoByKlsIDUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetFullAddressInfoByKlsIDUsingGETParamsWithTimeout(timeout time.Duration) *GetFullAddressInfoByKlsIDUsingGETParams {
	var ()
	return &GetFullAddressInfoByKlsIDUsingGETParams{

		timeout: timeout,
	}
}

// NewGetFullAddressInfoByKlsIDUsingGETParamsWithContext creates a new GetFullAddressInfoByKlsIDUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetFullAddressInfoByKlsIDUsingGETParamsWithContext(ctx context.Context) *GetFullAddressInfoByKlsIDUsingGETParams {
	var ()
	return &GetFullAddressInfoByKlsIDUsingGETParams{

		Context: ctx,
	}
}

// NewGetFullAddressInfoByKlsIDUsingGETParamsWithHTTPClient creates a new GetFullAddressInfoByKlsIDUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetFullAddressInfoByKlsIDUsingGETParamsWithHTTPClient(client *http.Client) *GetFullAddressInfoByKlsIDUsingGETParams {
	var ()
	return &GetFullAddressInfoByKlsIDUsingGETParams{
		HTTPClient: client,
	}
}

/*GetFullAddressInfoByKlsIDUsingGETParams contains all the parameters to send to the API endpoint
for the get full address info by kls Id using g e t operation typically these are written to a http.Request
*/
type GetFullAddressInfoByKlsIDUsingGETParams struct {

	/*KlsID
	  KlsId of the address

	*/
	KlsID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get full address info by kls Id using g e t params
func (o *GetFullAddressInfoByKlsIDUsingGETParams) WithTimeout(timeout time.Duration) *GetFullAddressInfoByKlsIDUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get full address info by kls Id using g e t params
func (o *GetFullAddressInfoByKlsIDUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get full address info by kls Id using g e t params
func (o *GetFullAddressInfoByKlsIDUsingGETParams) WithContext(ctx context.Context) *GetFullAddressInfoByKlsIDUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get full address info by kls Id using g e t params
func (o *GetFullAddressInfoByKlsIDUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get full address info by kls Id using g e t params
func (o *GetFullAddressInfoByKlsIDUsingGETParams) WithHTTPClient(client *http.Client) *GetFullAddressInfoByKlsIDUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get full address info by kls Id using g e t params
func (o *GetFullAddressInfoByKlsIDUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKlsID adds the klsID to the get full address info by kls Id using g e t params
func (o *GetFullAddressInfoByKlsIDUsingGETParams) WithKlsID(klsID int64) *GetFullAddressInfoByKlsIDUsingGETParams {
	o.SetKlsID(klsID)
	return o
}

// SetKlsID adds the klsId to the get full address info by kls Id using g e t params
func (o *GetFullAddressInfoByKlsIDUsingGETParams) SetKlsID(klsID int64) {
	o.KlsID = klsID
}

// WriteToRequest writes these params to a swagger request
func (o *GetFullAddressInfoByKlsIDUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param klsId
	if err := r.SetPathParam("klsId", swag.FormatInt64(o.KlsID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
