// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// SearchFullAddressInfoUsingPOSTReader is a Reader for the SearchFullAddressInfoUsingPOST structure.
type SearchFullAddressInfoUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchFullAddressInfoUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchFullAddressInfoUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewSearchFullAddressInfoUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSearchFullAddressInfoUsingPOSTBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSearchFullAddressInfoUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSearchFullAddressInfoUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSearchFullAddressInfoUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSearchFullAddressInfoUsingPOSTInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearchFullAddressInfoUsingPOSTOK creates a SearchFullAddressInfoUsingPOSTOK with default headers values
func NewSearchFullAddressInfoUsingPOSTOK() *SearchFullAddressInfoUsingPOSTOK {
	return &SearchFullAddressInfoUsingPOSTOK{}
}

/*SearchFullAddressInfoUsingPOSTOK handles this case with default header values.

Information was found.
*/
type SearchFullAddressInfoUsingPOSTOK struct {
	Payload []*models.FullAddressInfo
}

func (o *SearchFullAddressInfoUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getFullAddressInfo/search][%d] searchFullAddressInfoUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *SearchFullAddressInfoUsingPOSTOK) GetPayload() []*models.FullAddressInfo {
	return o.Payload
}

func (o *SearchFullAddressInfoUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchFullAddressInfoUsingPOSTCreated creates a SearchFullAddressInfoUsingPOSTCreated with default headers values
func NewSearchFullAddressInfoUsingPOSTCreated() *SearchFullAddressInfoUsingPOSTCreated {
	return &SearchFullAddressInfoUsingPOSTCreated{}
}

/*SearchFullAddressInfoUsingPOSTCreated handles this case with default header values.

Created
*/
type SearchFullAddressInfoUsingPOSTCreated struct {
}

func (o *SearchFullAddressInfoUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getFullAddressInfo/search][%d] searchFullAddressInfoUsingPOSTCreated ", 201)
}

func (o *SearchFullAddressInfoUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSearchFullAddressInfoUsingPOSTBadRequest creates a SearchFullAddressInfoUsingPOSTBadRequest with default headers values
func NewSearchFullAddressInfoUsingPOSTBadRequest() *SearchFullAddressInfoUsingPOSTBadRequest {
	return &SearchFullAddressInfoUsingPOSTBadRequest{}
}

/*SearchFullAddressInfoUsingPOSTBadRequest handles this case with default header values.

Bad request.
*/
type SearchFullAddressInfoUsingPOSTBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *SearchFullAddressInfoUsingPOSTBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getFullAddressInfo/search][%d] searchFullAddressInfoUsingPOSTBadRequest  %+v", 400, o.Payload)
}

func (o *SearchFullAddressInfoUsingPOSTBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *SearchFullAddressInfoUsingPOSTBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchFullAddressInfoUsingPOSTUnauthorized creates a SearchFullAddressInfoUsingPOSTUnauthorized with default headers values
func NewSearchFullAddressInfoUsingPOSTUnauthorized() *SearchFullAddressInfoUsingPOSTUnauthorized {
	return &SearchFullAddressInfoUsingPOSTUnauthorized{}
}

/*SearchFullAddressInfoUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type SearchFullAddressInfoUsingPOSTUnauthorized struct {
}

func (o *SearchFullAddressInfoUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getFullAddressInfo/search][%d] searchFullAddressInfoUsingPOSTUnauthorized ", 401)
}

func (o *SearchFullAddressInfoUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSearchFullAddressInfoUsingPOSTForbidden creates a SearchFullAddressInfoUsingPOSTForbidden with default headers values
func NewSearchFullAddressInfoUsingPOSTForbidden() *SearchFullAddressInfoUsingPOSTForbidden {
	return &SearchFullAddressInfoUsingPOSTForbidden{}
}

/*SearchFullAddressInfoUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type SearchFullAddressInfoUsingPOSTForbidden struct {
}

func (o *SearchFullAddressInfoUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getFullAddressInfo/search][%d] searchFullAddressInfoUsingPOSTForbidden ", 403)
}

func (o *SearchFullAddressInfoUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSearchFullAddressInfoUsingPOSTNotFound creates a SearchFullAddressInfoUsingPOSTNotFound with default headers values
func NewSearchFullAddressInfoUsingPOSTNotFound() *SearchFullAddressInfoUsingPOSTNotFound {
	return &SearchFullAddressInfoUsingPOSTNotFound{}
}

/*SearchFullAddressInfoUsingPOSTNotFound handles this case with default header values.

Address information was not found.
*/
type SearchFullAddressInfoUsingPOSTNotFound struct {
	Payload *models.ProblemDetails
}

func (o *SearchFullAddressInfoUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getFullAddressInfo/search][%d] searchFullAddressInfoUsingPOSTNotFound  %+v", 404, o.Payload)
}

func (o *SearchFullAddressInfoUsingPOSTNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *SearchFullAddressInfoUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchFullAddressInfoUsingPOSTInternalServerError creates a SearchFullAddressInfoUsingPOSTInternalServerError with default headers values
func NewSearchFullAddressInfoUsingPOSTInternalServerError() *SearchFullAddressInfoUsingPOSTInternalServerError {
	return &SearchFullAddressInfoUsingPOSTInternalServerError{}
}

/*SearchFullAddressInfoUsingPOSTInternalServerError handles this case with default header values.

Internal Server Error.
*/
type SearchFullAddressInfoUsingPOSTInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *SearchFullAddressInfoUsingPOSTInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getFullAddressInfo/search][%d] searchFullAddressInfoUsingPOSTInternalServerError  %+v", 500, o.Payload)
}

func (o *SearchFullAddressInfoUsingPOSTInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *SearchFullAddressInfoUsingPOSTInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
