// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// NewSearchFullAddressInfoUsingPOSTParams creates a new SearchFullAddressInfoUsingPOSTParams object
// with the default values initialized.
func NewSearchFullAddressInfoUsingPOSTParams() *SearchFullAddressInfoUsingPOSTParams {
	var ()
	return &SearchFullAddressInfoUsingPOSTParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSearchFullAddressInfoUsingPOSTParamsWithTimeout creates a new SearchFullAddressInfoUsingPOSTParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSearchFullAddressInfoUsingPOSTParamsWithTimeout(timeout time.Duration) *SearchFullAddressInfoUsingPOSTParams {
	var ()
	return &SearchFullAddressInfoUsingPOSTParams{

		timeout: timeout,
	}
}

// NewSearchFullAddressInfoUsingPOSTParamsWithContext creates a new SearchFullAddressInfoUsingPOSTParams object
// with the default values initialized, and the ability to set a context for a request
func NewSearchFullAddressInfoUsingPOSTParamsWithContext(ctx context.Context) *SearchFullAddressInfoUsingPOSTParams {
	var ()
	return &SearchFullAddressInfoUsingPOSTParams{

		Context: ctx,
	}
}

// NewSearchFullAddressInfoUsingPOSTParamsWithHTTPClient creates a new SearchFullAddressInfoUsingPOSTParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSearchFullAddressInfoUsingPOSTParamsWithHTTPClient(client *http.Client) *SearchFullAddressInfoUsingPOSTParams {
	var ()
	return &SearchFullAddressInfoUsingPOSTParams{
		HTTPClient: client,
	}
}

/*SearchFullAddressInfoUsingPOSTParams contains all the parameters to send to the API endpoint
for the search full address info using p o s t operation typically these are written to a http.Request
*/
type SearchFullAddressInfoUsingPOSTParams struct {

	/*Criteria
	  Address search criteria

	*/
	Criteria *models.AddressSearchCriteria

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the search full address info using p o s t params
func (o *SearchFullAddressInfoUsingPOSTParams) WithTimeout(timeout time.Duration) *SearchFullAddressInfoUsingPOSTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the search full address info using p o s t params
func (o *SearchFullAddressInfoUsingPOSTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the search full address info using p o s t params
func (o *SearchFullAddressInfoUsingPOSTParams) WithContext(ctx context.Context) *SearchFullAddressInfoUsingPOSTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the search full address info using p o s t params
func (o *SearchFullAddressInfoUsingPOSTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the search full address info using p o s t params
func (o *SearchFullAddressInfoUsingPOSTParams) WithHTTPClient(client *http.Client) *SearchFullAddressInfoUsingPOSTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the search full address info using p o s t params
func (o *SearchFullAddressInfoUsingPOSTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCriteria adds the criteria to the search full address info using p o s t params
func (o *SearchFullAddressInfoUsingPOSTParams) WithCriteria(criteria *models.AddressSearchCriteria) *SearchFullAddressInfoUsingPOSTParams {
	o.SetCriteria(criteria)
	return o
}

// SetCriteria adds the criteria to the search full address info using p o s t params
func (o *SearchFullAddressInfoUsingPOSTParams) SetCriteria(criteria *models.AddressSearchCriteria) {
	o.Criteria = criteria
}

// WriteToRequest writes these params to a swagger request
func (o *SearchFullAddressInfoUsingPOSTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Criteria != nil {
		if err := r.SetBodyParam(o.Criteria); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
