// Code generated by go-swagger; DO NOT EDIT.

package address_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// SearchAddressInfoUsingPOSTReader is a Reader for the SearchAddressInfoUsingPOST structure.
type SearchAddressInfoUsingPOSTReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchAddressInfoUsingPOSTReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSearchAddressInfoUsingPOSTOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewSearchAddressInfoUsingPOSTCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSearchAddressInfoUsingPOSTBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewSearchAddressInfoUsingPOSTUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSearchAddressInfoUsingPOSTForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSearchAddressInfoUsingPOSTNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSearchAddressInfoUsingPOSTInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSearchAddressInfoUsingPOSTOK creates a SearchAddressInfoUsingPOSTOK with default headers values
func NewSearchAddressInfoUsingPOSTOK() *SearchAddressInfoUsingPOSTOK {
	return &SearchAddressInfoUsingPOSTOK{}
}

/*SearchAddressInfoUsingPOSTOK handles this case with default header values.

Information was found.
*/
type SearchAddressInfoUsingPOSTOK struct {
	Payload []*models.AddressInfo
}

func (o *SearchAddressInfoUsingPOSTOK) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getAddressInfo/search][%d] searchAddressInfoUsingPOSTOK  %+v", 200, o.Payload)
}

func (o *SearchAddressInfoUsingPOSTOK) GetPayload() []*models.AddressInfo {
	return o.Payload
}

func (o *SearchAddressInfoUsingPOSTOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchAddressInfoUsingPOSTCreated creates a SearchAddressInfoUsingPOSTCreated with default headers values
func NewSearchAddressInfoUsingPOSTCreated() *SearchAddressInfoUsingPOSTCreated {
	return &SearchAddressInfoUsingPOSTCreated{}
}

/*SearchAddressInfoUsingPOSTCreated handles this case with default header values.

Created
*/
type SearchAddressInfoUsingPOSTCreated struct {
}

func (o *SearchAddressInfoUsingPOSTCreated) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getAddressInfo/search][%d] searchAddressInfoUsingPOSTCreated ", 201)
}

func (o *SearchAddressInfoUsingPOSTCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSearchAddressInfoUsingPOSTBadRequest creates a SearchAddressInfoUsingPOSTBadRequest with default headers values
func NewSearchAddressInfoUsingPOSTBadRequest() *SearchAddressInfoUsingPOSTBadRequest {
	return &SearchAddressInfoUsingPOSTBadRequest{}
}

/*SearchAddressInfoUsingPOSTBadRequest handles this case with default header values.

Bad request.
*/
type SearchAddressInfoUsingPOSTBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *SearchAddressInfoUsingPOSTBadRequest) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getAddressInfo/search][%d] searchAddressInfoUsingPOSTBadRequest  %+v", 400, o.Payload)
}

func (o *SearchAddressInfoUsingPOSTBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *SearchAddressInfoUsingPOSTBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchAddressInfoUsingPOSTUnauthorized creates a SearchAddressInfoUsingPOSTUnauthorized with default headers values
func NewSearchAddressInfoUsingPOSTUnauthorized() *SearchAddressInfoUsingPOSTUnauthorized {
	return &SearchAddressInfoUsingPOSTUnauthorized{}
}

/*SearchAddressInfoUsingPOSTUnauthorized handles this case with default header values.

Unauthorized
*/
type SearchAddressInfoUsingPOSTUnauthorized struct {
}

func (o *SearchAddressInfoUsingPOSTUnauthorized) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getAddressInfo/search][%d] searchAddressInfoUsingPOSTUnauthorized ", 401)
}

func (o *SearchAddressInfoUsingPOSTUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSearchAddressInfoUsingPOSTForbidden creates a SearchAddressInfoUsingPOSTForbidden with default headers values
func NewSearchAddressInfoUsingPOSTForbidden() *SearchAddressInfoUsingPOSTForbidden {
	return &SearchAddressInfoUsingPOSTForbidden{}
}

/*SearchAddressInfoUsingPOSTForbidden handles this case with default header values.

Forbidden
*/
type SearchAddressInfoUsingPOSTForbidden struct {
}

func (o *SearchAddressInfoUsingPOSTForbidden) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getAddressInfo/search][%d] searchAddressInfoUsingPOSTForbidden ", 403)
}

func (o *SearchAddressInfoUsingPOSTForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSearchAddressInfoUsingPOSTNotFound creates a SearchAddressInfoUsingPOSTNotFound with default headers values
func NewSearchAddressInfoUsingPOSTNotFound() *SearchAddressInfoUsingPOSTNotFound {
	return &SearchAddressInfoUsingPOSTNotFound{}
}

/*SearchAddressInfoUsingPOSTNotFound handles this case with default header values.

Address information was not found.
*/
type SearchAddressInfoUsingPOSTNotFound struct {
	Payload *models.ProblemDetails
}

func (o *SearchAddressInfoUsingPOSTNotFound) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getAddressInfo/search][%d] searchAddressInfoUsingPOSTNotFound  %+v", 404, o.Payload)
}

func (o *SearchAddressInfoUsingPOSTNotFound) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *SearchAddressInfoUsingPOSTNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchAddressInfoUsingPOSTInternalServerError creates a SearchAddressInfoUsingPOSTInternalServerError with default headers values
func NewSearchAddressInfoUsingPOSTInternalServerError() *SearchAddressInfoUsingPOSTInternalServerError {
	return &SearchAddressInfoUsingPOSTInternalServerError{}
}

/*SearchAddressInfoUsingPOSTInternalServerError handles this case with default header values.

Internal Server Error.
*/
type SearchAddressInfoUsingPOSTInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *SearchAddressInfoUsingPOSTInternalServerError) Error() string {
	return fmt.Sprintf("[POST /api/addressLookup/v1/addressSearch/getAddressInfo/search][%d] searchAddressInfoUsingPOSTInternalServerError  %+v", 500, o.Payload)
}

func (o *SearchAddressInfoUsingPOSTInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *SearchAddressInfoUsingPOSTInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
