// Code generated by go-swagger; DO NOT EDIT.

package geoposition_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAddressesByCoordinateBoundsUsingGETParams creates a new GetAddressesByCoordinateBoundsUsingGETParams object
// with the default values initialized.
func NewGetAddressesByCoordinateBoundsUsingGETParams() *GetAddressesByCoordinateBoundsUsingGETParams {
	var ()
	return &GetAddressesByCoordinateBoundsUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAddressesByCoordinateBoundsUsingGETParamsWithTimeout creates a new GetAddressesByCoordinateBoundsUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAddressesByCoordinateBoundsUsingGETParamsWithTimeout(timeout time.Duration) *GetAddressesByCoordinateBoundsUsingGETParams {
	var ()
	return &GetAddressesByCoordinateBoundsUsingGETParams{

		timeout: timeout,
	}
}

// NewGetAddressesByCoordinateBoundsUsingGETParamsWithContext creates a new GetAddressesByCoordinateBoundsUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetAddressesByCoordinateBoundsUsingGETParamsWithContext(ctx context.Context) *GetAddressesByCoordinateBoundsUsingGETParams {
	var ()
	return &GetAddressesByCoordinateBoundsUsingGETParams{

		Context: ctx,
	}
}

// NewGetAddressesByCoordinateBoundsUsingGETParamsWithHTTPClient creates a new GetAddressesByCoordinateBoundsUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAddressesByCoordinateBoundsUsingGETParamsWithHTTPClient(client *http.Client) *GetAddressesByCoordinateBoundsUsingGETParams {
	var ()
	return &GetAddressesByCoordinateBoundsUsingGETParams{
		HTTPClient: client,
	}
}

/*GetAddressesByCoordinateBoundsUsingGETParams contains all the parameters to send to the API endpoint
for the get addresses by coordinate bounds using g e t operation typically these are written to a http.Request
*/
type GetAddressesByCoordinateBoundsUsingGETParams struct {

	/*EastBound
	  eastBound

	*/
	EastBound *float64
	/*NorthBound
	  northBound

	*/
	NorthBound *float64
	/*SouthBound
	  southBound

	*/
	SouthBound *float64
	/*WestBound
	  westBound

	*/
	WestBound *float64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) WithTimeout(timeout time.Duration) *GetAddressesByCoordinateBoundsUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) WithContext(ctx context.Context) *GetAddressesByCoordinateBoundsUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) WithHTTPClient(client *http.Client) *GetAddressesByCoordinateBoundsUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithEastBound adds the eastBound to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) WithEastBound(eastBound *float64) *GetAddressesByCoordinateBoundsUsingGETParams {
	o.SetEastBound(eastBound)
	return o
}

// SetEastBound adds the eastBound to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) SetEastBound(eastBound *float64) {
	o.EastBound = eastBound
}

// WithNorthBound adds the northBound to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) WithNorthBound(northBound *float64) *GetAddressesByCoordinateBoundsUsingGETParams {
	o.SetNorthBound(northBound)
	return o
}

// SetNorthBound adds the northBound to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) SetNorthBound(northBound *float64) {
	o.NorthBound = northBound
}

// WithSouthBound adds the southBound to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) WithSouthBound(southBound *float64) *GetAddressesByCoordinateBoundsUsingGETParams {
	o.SetSouthBound(southBound)
	return o
}

// SetSouthBound adds the southBound to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) SetSouthBound(southBound *float64) {
	o.SouthBound = southBound
}

// WithWestBound adds the westBound to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) WithWestBound(westBound *float64) *GetAddressesByCoordinateBoundsUsingGETParams {
	o.SetWestBound(westBound)
	return o
}

// SetWestBound adds the westBound to the get addresses by coordinate bounds using g e t params
func (o *GetAddressesByCoordinateBoundsUsingGETParams) SetWestBound(westBound *float64) {
	o.WestBound = westBound
}

// WriteToRequest writes these params to a swagger request
func (o *GetAddressesByCoordinateBoundsUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.EastBound != nil {

		// query param eastBound
		var qrEastBound float64
		if o.EastBound != nil {
			qrEastBound = *o.EastBound
		}
		qEastBound := swag.FormatFloat64(qrEastBound)
		if qEastBound != "" {
			if err := r.SetQueryParam("eastBound", qEastBound); err != nil {
				return err
			}
		}

	}

	if o.NorthBound != nil {

		// query param northBound
		var qrNorthBound float64
		if o.NorthBound != nil {
			qrNorthBound = *o.NorthBound
		}
		qNorthBound := swag.FormatFloat64(qrNorthBound)
		if qNorthBound != "" {
			if err := r.SetQueryParam("northBound", qNorthBound); err != nil {
				return err
			}
		}

	}

	if o.SouthBound != nil {

		// query param southBound
		var qrSouthBound float64
		if o.SouthBound != nil {
			qrSouthBound = *o.SouthBound
		}
		qSouthBound := swag.FormatFloat64(qrSouthBound)
		if qSouthBound != "" {
			if err := r.SetQueryParam("southBound", qSouthBound); err != nil {
				return err
			}
		}

	}

	if o.WestBound != nil {

		// query param westBound
		var qrWestBound float64
		if o.WestBound != nil {
			qrWestBound = *o.WestBound
		}
		qWestBound := swag.FormatFloat64(qrWestBound)
		if qWestBound != "" {
			if err := r.SetQueryParam("westBound", qWestBound); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
