// Code generated by go-swagger; DO NOT EDIT.

package geoposition_services

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// GetAddressesByCoordinateBoundsUsingGETReader is a Reader for the GetAddressesByCoordinateBoundsUsingGET structure.
type GetAddressesByCoordinateBoundsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAddressesByCoordinateBoundsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAddressesByCoordinateBoundsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAddressesByCoordinateBoundsUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAddressesByCoordinateBoundsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAddressesByCoordinateBoundsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAddressesByCoordinateBoundsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAddressesByCoordinateBoundsUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAddressesByCoordinateBoundsUsingGETOK creates a GetAddressesByCoordinateBoundsUsingGETOK with default headers values
func NewGetAddressesByCoordinateBoundsUsingGETOK() *GetAddressesByCoordinateBoundsUsingGETOK {
	return &GetAddressesByCoordinateBoundsUsingGETOK{}
}

/*GetAddressesByCoordinateBoundsUsingGETOK handles this case with default header values.

Information was found.
*/
type GetAddressesByCoordinateBoundsUsingGETOK struct {
	Payload []*models.AddressSuggestion
}

func (o *GetAddressesByCoordinateBoundsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addresses/geopositions/coordinateBounds][%d] getAddressesByCoordinateBoundsUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetAddressesByCoordinateBoundsUsingGETOK) GetPayload() []*models.AddressSuggestion {
	return o.Payload
}

func (o *GetAddressesByCoordinateBoundsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAddressesByCoordinateBoundsUsingGETBadRequest creates a GetAddressesByCoordinateBoundsUsingGETBadRequest with default headers values
func NewGetAddressesByCoordinateBoundsUsingGETBadRequest() *GetAddressesByCoordinateBoundsUsingGETBadRequest {
	return &GetAddressesByCoordinateBoundsUsingGETBadRequest{}
}

/*GetAddressesByCoordinateBoundsUsingGETBadRequest handles this case with default header values.

Bad request.
*/
type GetAddressesByCoordinateBoundsUsingGETBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *GetAddressesByCoordinateBoundsUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addresses/geopositions/coordinateBounds][%d] getAddressesByCoordinateBoundsUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *GetAddressesByCoordinateBoundsUsingGETBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetAddressesByCoordinateBoundsUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAddressesByCoordinateBoundsUsingGETUnauthorized creates a GetAddressesByCoordinateBoundsUsingGETUnauthorized with default headers values
func NewGetAddressesByCoordinateBoundsUsingGETUnauthorized() *GetAddressesByCoordinateBoundsUsingGETUnauthorized {
	return &GetAddressesByCoordinateBoundsUsingGETUnauthorized{}
}

/*GetAddressesByCoordinateBoundsUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAddressesByCoordinateBoundsUsingGETUnauthorized struct {
}

func (o *GetAddressesByCoordinateBoundsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addresses/geopositions/coordinateBounds][%d] getAddressesByCoordinateBoundsUsingGETUnauthorized ", 401)
}

func (o *GetAddressesByCoordinateBoundsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAddressesByCoordinateBoundsUsingGETForbidden creates a GetAddressesByCoordinateBoundsUsingGETForbidden with default headers values
func NewGetAddressesByCoordinateBoundsUsingGETForbidden() *GetAddressesByCoordinateBoundsUsingGETForbidden {
	return &GetAddressesByCoordinateBoundsUsingGETForbidden{}
}

/*GetAddressesByCoordinateBoundsUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetAddressesByCoordinateBoundsUsingGETForbidden struct {
}

func (o *GetAddressesByCoordinateBoundsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addresses/geopositions/coordinateBounds][%d] getAddressesByCoordinateBoundsUsingGETForbidden ", 403)
}

func (o *GetAddressesByCoordinateBoundsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAddressesByCoordinateBoundsUsingGETNotFound creates a GetAddressesByCoordinateBoundsUsingGETNotFound with default headers values
func NewGetAddressesByCoordinateBoundsUsingGETNotFound() *GetAddressesByCoordinateBoundsUsingGETNotFound {
	return &GetAddressesByCoordinateBoundsUsingGETNotFound{}
}

/*GetAddressesByCoordinateBoundsUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetAddressesByCoordinateBoundsUsingGETNotFound struct {
}

func (o *GetAddressesByCoordinateBoundsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addresses/geopositions/coordinateBounds][%d] getAddressesByCoordinateBoundsUsingGETNotFound ", 404)
}

func (o *GetAddressesByCoordinateBoundsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAddressesByCoordinateBoundsUsingGETInternalServerError creates a GetAddressesByCoordinateBoundsUsingGETInternalServerError with default headers values
func NewGetAddressesByCoordinateBoundsUsingGETInternalServerError() *GetAddressesByCoordinateBoundsUsingGETInternalServerError {
	return &GetAddressesByCoordinateBoundsUsingGETInternalServerError{}
}

/*GetAddressesByCoordinateBoundsUsingGETInternalServerError handles this case with default header values.

Internal Server Error.
*/
type GetAddressesByCoordinateBoundsUsingGETInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *GetAddressesByCoordinateBoundsUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addresses/geopositions/coordinateBounds][%d] getAddressesByCoordinateBoundsUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAddressesByCoordinateBoundsUsingGETInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetAddressesByCoordinateBoundsUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
