// Code generated by go-swagger; DO NOT EDIT.

package address_deprecated_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// GetDeprecatedAddressByIDUsingGETReader is a Reader for the GetDeprecatedAddressByIDUsingGET structure.
type GetDeprecatedAddressByIDUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetDeprecatedAddressByIDUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetDeprecatedAddressByIDUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetDeprecatedAddressByIDUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetDeprecatedAddressByIDUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetDeprecatedAddressByIDUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetDeprecatedAddressByIDUsingGETOK creates a GetDeprecatedAddressByIDUsingGETOK with default headers values
func NewGetDeprecatedAddressByIDUsingGETOK() *GetDeprecatedAddressByIDUsingGETOK {
	return &GetDeprecatedAddressByIDUsingGETOK{}
}

/*GetDeprecatedAddressByIDUsingGETOK handles this case with default header values.

OK
*/
type GetDeprecatedAddressByIDUsingGETOK struct {
	Payload *models.Address
}

func (o *GetDeprecatedAddressByIDUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/address-lookup/addresses/{klsId}][%d] getDeprecatedAddressByIdUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetDeprecatedAddressByIDUsingGETOK) GetPayload() *models.Address {
	return o.Payload
}

func (o *GetDeprecatedAddressByIDUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Address)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetDeprecatedAddressByIDUsingGETUnauthorized creates a GetDeprecatedAddressByIDUsingGETUnauthorized with default headers values
func NewGetDeprecatedAddressByIDUsingGETUnauthorized() *GetDeprecatedAddressByIDUsingGETUnauthorized {
	return &GetDeprecatedAddressByIDUsingGETUnauthorized{}
}

/*GetDeprecatedAddressByIDUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetDeprecatedAddressByIDUsingGETUnauthorized struct {
}

func (o *GetDeprecatedAddressByIDUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/address-lookup/addresses/{klsId}][%d] getDeprecatedAddressByIdUsingGETUnauthorized ", 401)
}

func (o *GetDeprecatedAddressByIDUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeprecatedAddressByIDUsingGETForbidden creates a GetDeprecatedAddressByIDUsingGETForbidden with default headers values
func NewGetDeprecatedAddressByIDUsingGETForbidden() *GetDeprecatedAddressByIDUsingGETForbidden {
	return &GetDeprecatedAddressByIDUsingGETForbidden{}
}

/*GetDeprecatedAddressByIDUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetDeprecatedAddressByIDUsingGETForbidden struct {
}

func (o *GetDeprecatedAddressByIDUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/address-lookup/addresses/{klsId}][%d] getDeprecatedAddressByIdUsingGETForbidden ", 403)
}

func (o *GetDeprecatedAddressByIDUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetDeprecatedAddressByIDUsingGETNotFound creates a GetDeprecatedAddressByIDUsingGETNotFound with default headers values
func NewGetDeprecatedAddressByIDUsingGETNotFound() *GetDeprecatedAddressByIDUsingGETNotFound {
	return &GetDeprecatedAddressByIDUsingGETNotFound{}
}

/*GetDeprecatedAddressByIDUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetDeprecatedAddressByIDUsingGETNotFound struct {
}

func (o *GetDeprecatedAddressByIDUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/address-lookup/addresses/{klsId}][%d] getDeprecatedAddressByIdUsingGETNotFound ", 404)
}

func (o *GetDeprecatedAddressByIDUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
