// Code generated by go-swagger; DO NOT EDIT.

package address_deprecated_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// SuggestDeprecatedHousenumbersUsingGETReader is a Reader for the SuggestDeprecatedHousenumbersUsingGET structure.
type SuggestDeprecatedHousenumbersUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SuggestDeprecatedHousenumbersUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSuggestDeprecatedHousenumbersUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewSuggestDeprecatedHousenumbersUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewSuggestDeprecatedHousenumbersUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSuggestDeprecatedHousenumbersUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSuggestDeprecatedHousenumbersUsingGETOK creates a SuggestDeprecatedHousenumbersUsingGETOK with default headers values
func NewSuggestDeprecatedHousenumbersUsingGETOK() *SuggestDeprecatedHousenumbersUsingGETOK {
	return &SuggestDeprecatedHousenumbersUsingGETOK{}
}

/*SuggestDeprecatedHousenumbersUsingGETOK handles this case with default header values.

OK
*/
type SuggestDeprecatedHousenumbersUsingGETOK struct {
	Payload []*models.Address
}

func (o *SuggestDeprecatedHousenumbersUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/address-lookup/streetnumbers][%d] suggestDeprecatedHousenumbersUsingGETOK  %+v", 200, o.Payload)
}

func (o *SuggestDeprecatedHousenumbersUsingGETOK) GetPayload() []*models.Address {
	return o.Payload
}

func (o *SuggestDeprecatedHousenumbersUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSuggestDeprecatedHousenumbersUsingGETUnauthorized creates a SuggestDeprecatedHousenumbersUsingGETUnauthorized with default headers values
func NewSuggestDeprecatedHousenumbersUsingGETUnauthorized() *SuggestDeprecatedHousenumbersUsingGETUnauthorized {
	return &SuggestDeprecatedHousenumbersUsingGETUnauthorized{}
}

/*SuggestDeprecatedHousenumbersUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type SuggestDeprecatedHousenumbersUsingGETUnauthorized struct {
}

func (o *SuggestDeprecatedHousenumbersUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/address-lookup/streetnumbers][%d] suggestDeprecatedHousenumbersUsingGETUnauthorized ", 401)
}

func (o *SuggestDeprecatedHousenumbersUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSuggestDeprecatedHousenumbersUsingGETForbidden creates a SuggestDeprecatedHousenumbersUsingGETForbidden with default headers values
func NewSuggestDeprecatedHousenumbersUsingGETForbidden() *SuggestDeprecatedHousenumbersUsingGETForbidden {
	return &SuggestDeprecatedHousenumbersUsingGETForbidden{}
}

/*SuggestDeprecatedHousenumbersUsingGETForbidden handles this case with default header values.

Forbidden
*/
type SuggestDeprecatedHousenumbersUsingGETForbidden struct {
}

func (o *SuggestDeprecatedHousenumbersUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/address-lookup/streetnumbers][%d] suggestDeprecatedHousenumbersUsingGETForbidden ", 403)
}

func (o *SuggestDeprecatedHousenumbersUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSuggestDeprecatedHousenumbersUsingGETNotFound creates a SuggestDeprecatedHousenumbersUsingGETNotFound with default headers values
func NewSuggestDeprecatedHousenumbersUsingGETNotFound() *SuggestDeprecatedHousenumbersUsingGETNotFound {
	return &SuggestDeprecatedHousenumbersUsingGETNotFound{}
}

/*SuggestDeprecatedHousenumbersUsingGETNotFound handles this case with default header values.

Not Found
*/
type SuggestDeprecatedHousenumbersUsingGETNotFound struct {
}

func (o *SuggestDeprecatedHousenumbersUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1.0/address-lookup/streetnumbers][%d] suggestDeprecatedHousenumbersUsingGETNotFound ", 404)
}

func (o *SuggestDeprecatedHousenumbersUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
