// Code generated by go-swagger; DO NOT EDIT.

package address_deprecated_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSuggestDeprecatedHousenumbersUsingGETParams creates a new SuggestDeprecatedHousenumbersUsingGETParams object
// with the default values initialized.
func NewSuggestDeprecatedHousenumbersUsingGETParams() *SuggestDeprecatedHousenumbersUsingGETParams {
	var ()
	return &SuggestDeprecatedHousenumbersUsingGETParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSuggestDeprecatedHousenumbersUsingGETParamsWithTimeout creates a new SuggestDeprecatedHousenumbersUsingGETParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSuggestDeprecatedHousenumbersUsingGETParamsWithTimeout(timeout time.Duration) *SuggestDeprecatedHousenumbersUsingGETParams {
	var ()
	return &SuggestDeprecatedHousenumbersUsingGETParams{

		timeout: timeout,
	}
}

// NewSuggestDeprecatedHousenumbersUsingGETParamsWithContext creates a new SuggestDeprecatedHousenumbersUsingGETParams object
// with the default values initialized, and the ability to set a context for a request
func NewSuggestDeprecatedHousenumbersUsingGETParamsWithContext(ctx context.Context) *SuggestDeprecatedHousenumbersUsingGETParams {
	var ()
	return &SuggestDeprecatedHousenumbersUsingGETParams{

		Context: ctx,
	}
}

// NewSuggestDeprecatedHousenumbersUsingGETParamsWithHTTPClient creates a new SuggestDeprecatedHousenumbersUsingGETParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSuggestDeprecatedHousenumbersUsingGETParamsWithHTTPClient(client *http.Client) *SuggestDeprecatedHousenumbersUsingGETParams {
	var ()
	return &SuggestDeprecatedHousenumbersUsingGETParams{
		HTTPClient: client,
	}
}

/*SuggestDeprecatedHousenumbersUsingGETParams contains all the parameters to send to the API endpoint
for the suggest deprecated housenumbers using g e t operation typically these are written to a http.Request
*/
type SuggestDeprecatedHousenumbersUsingGETParams struct {

	/*City
	  City to filter addresses

	*/
	City string
	/*Street
	  Street to filter addresses

	*/
	Street string
	/*Streetnumber
	  Token to autocomplete

	*/
	Streetnumber string
	/*Zipcode
	  Zipcode to filter addresses

	*/
	Zipcode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) WithTimeout(timeout time.Duration) *SuggestDeprecatedHousenumbersUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) WithContext(ctx context.Context) *SuggestDeprecatedHousenumbersUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) WithHTTPClient(client *http.Client) *SuggestDeprecatedHousenumbersUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCity adds the city to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) WithCity(city string) *SuggestDeprecatedHousenumbersUsingGETParams {
	o.SetCity(city)
	return o
}

// SetCity adds the city to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) SetCity(city string) {
	o.City = city
}

// WithStreet adds the street to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) WithStreet(street string) *SuggestDeprecatedHousenumbersUsingGETParams {
	o.SetStreet(street)
	return o
}

// SetStreet adds the street to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) SetStreet(street string) {
	o.Street = street
}

// WithStreetnumber adds the streetnumber to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) WithStreetnumber(streetnumber string) *SuggestDeprecatedHousenumbersUsingGETParams {
	o.SetStreetnumber(streetnumber)
	return o
}

// SetStreetnumber adds the streetnumber to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) SetStreetnumber(streetnumber string) {
	o.Streetnumber = streetnumber
}

// WithZipcode adds the zipcode to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) WithZipcode(zipcode string) *SuggestDeprecatedHousenumbersUsingGETParams {
	o.SetZipcode(zipcode)
	return o
}

// SetZipcode adds the zipcode to the suggest deprecated housenumbers using g e t params
func (o *SuggestDeprecatedHousenumbersUsingGETParams) SetZipcode(zipcode string) {
	o.Zipcode = zipcode
}

// WriteToRequest writes these params to a swagger request
func (o *SuggestDeprecatedHousenumbersUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param city
	qrCity := o.City
	qCity := qrCity
	if qCity != "" {
		if err := r.SetQueryParam("city", qCity); err != nil {
			return err
		}
	}

	// query param street
	qrStreet := o.Street
	qStreet := qrStreet
	if qStreet != "" {
		if err := r.SetQueryParam("street", qStreet); err != nil {
			return err
		}
	}

	// query param streetnumber
	qrStreetnumber := o.Streetnumber
	qStreetnumber := qrStreetnumber
	if qStreetnumber != "" {
		if err := r.SetQueryParam("streetnumber", qStreetnumber); err != nil {
			return err
		}
	}

	// query param zipcode
	qrZipcode := o.Zipcode
	qZipcode := qrZipcode
	if qZipcode != "" {
		if err := r.SetQueryParam("zipcode", qZipcode); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
