// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/mkrill/diPrototypeWire/src/helpers"
	"github.com/mkrill/diPrototypeWire/src/infrastructure"
	"github.com/mkrill/diPrototypeWire/src/interfaces/controller"
)

// Injectors from wire.go:

func InitializeRealController(host helpers.Host, username helpers.Username, password helpers.Password) (*controller.RootController, error) {
	runtime, err := helpers.ProvideRuntimeClient(host, username, password)
	if err != nil {
		return nil, err
	}
	addressLookup := helpers.ProvideAdressLookupClient(runtime)
	realAddressService := infrastructure.ProvideRealAddressService(addressLookup)
	rootController, err := controller.ProvideController(realAddressService)
	if err != nil {
		return nil, err
	}
	return rootController, nil
}

func InitializeFakeController() (*controller.RootController, error) {
	fakeAddressService := infrastructure.ProvideFakeAddressService()
	rootController, err := controller.ProvideController(fakeAddressService)
	if err != nil {
		return nil, err
	}
	return rootController, nil
}
