// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/mkrill/diPrototypeWire/src/controller"
	"github.com/mkrill/diPrototypeWire/src/infrastructure"
	"github.com/mkrill/diPrototypeWire/src/providers"
)

// Injectors from wire.go:

func InitializeRealController(config providers.RuntimeConfig) (*controller.RootController, error) {
	runtime := providers.ProvideRuntimeClient(config)
	addressLookup := providers.ProvideAdressLookupClient(runtime)
	realAddressService := infrastructure.ProvideRealAddressService(addressLookup)
	rootController, err := controller.ProvideController(realAddressService)
	if err != nil {
		return nil, err
	}
	return rootController, nil
}

func InitializeFakeController() (*controller.RootController, error) {
	fakeAddressService := infrastructure.ProvideFakeAddressService()
	rootController, err := controller.ProvideController(fakeAddressService)
	if err != nil {
		return nil, err
	}
	return rootController, nil
}
