// Code generated by go-swagger; DO NOT EDIT.

package address_suggest_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/mkrill/diPrototypeWire/src/infrastructure/models"
)

// GetAddressSuggestionsUsingGETReader is a Reader for the GetAddressSuggestionsUsingGET structure.
type GetAddressSuggestionsUsingGETReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAddressSuggestionsUsingGETReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAddressSuggestionsUsingGETOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAddressSuggestionsUsingGETBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAddressSuggestionsUsingGETUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetAddressSuggestionsUsingGETForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetAddressSuggestionsUsingGETNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAddressSuggestionsUsingGETInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAddressSuggestionsUsingGETOK creates a GetAddressSuggestionsUsingGETOK with default headers values
func NewGetAddressSuggestionsUsingGETOK() *GetAddressSuggestionsUsingGETOK {
	return &GetAddressSuggestionsUsingGETOK{}
}

/*GetAddressSuggestionsUsingGETOK handles this case with default header values.

Information was found.
*/
type GetAddressSuggestionsUsingGETOK struct {
	Payload []*models.AddressSuggestion
}

func (o *GetAddressSuggestionsUsingGETOK) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addressSuggestions/][%d] getAddressSuggestionsUsingGETOK  %+v", 200, o.Payload)
}

func (o *GetAddressSuggestionsUsingGETOK) GetPayload() []*models.AddressSuggestion {
	return o.Payload
}

func (o *GetAddressSuggestionsUsingGETOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAddressSuggestionsUsingGETBadRequest creates a GetAddressSuggestionsUsingGETBadRequest with default headers values
func NewGetAddressSuggestionsUsingGETBadRequest() *GetAddressSuggestionsUsingGETBadRequest {
	return &GetAddressSuggestionsUsingGETBadRequest{}
}

/*GetAddressSuggestionsUsingGETBadRequest handles this case with default header values.

Bad request.
*/
type GetAddressSuggestionsUsingGETBadRequest struct {
	Payload *models.ProblemDetails
}

func (o *GetAddressSuggestionsUsingGETBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addressSuggestions/][%d] getAddressSuggestionsUsingGETBadRequest  %+v", 400, o.Payload)
}

func (o *GetAddressSuggestionsUsingGETBadRequest) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetAddressSuggestionsUsingGETBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAddressSuggestionsUsingGETUnauthorized creates a GetAddressSuggestionsUsingGETUnauthorized with default headers values
func NewGetAddressSuggestionsUsingGETUnauthorized() *GetAddressSuggestionsUsingGETUnauthorized {
	return &GetAddressSuggestionsUsingGETUnauthorized{}
}

/*GetAddressSuggestionsUsingGETUnauthorized handles this case with default header values.

Unauthorized
*/
type GetAddressSuggestionsUsingGETUnauthorized struct {
}

func (o *GetAddressSuggestionsUsingGETUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addressSuggestions/][%d] getAddressSuggestionsUsingGETUnauthorized ", 401)
}

func (o *GetAddressSuggestionsUsingGETUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAddressSuggestionsUsingGETForbidden creates a GetAddressSuggestionsUsingGETForbidden with default headers values
func NewGetAddressSuggestionsUsingGETForbidden() *GetAddressSuggestionsUsingGETForbidden {
	return &GetAddressSuggestionsUsingGETForbidden{}
}

/*GetAddressSuggestionsUsingGETForbidden handles this case with default header values.

Forbidden
*/
type GetAddressSuggestionsUsingGETForbidden struct {
}

func (o *GetAddressSuggestionsUsingGETForbidden) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addressSuggestions/][%d] getAddressSuggestionsUsingGETForbidden ", 403)
}

func (o *GetAddressSuggestionsUsingGETForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAddressSuggestionsUsingGETNotFound creates a GetAddressSuggestionsUsingGETNotFound with default headers values
func NewGetAddressSuggestionsUsingGETNotFound() *GetAddressSuggestionsUsingGETNotFound {
	return &GetAddressSuggestionsUsingGETNotFound{}
}

/*GetAddressSuggestionsUsingGETNotFound handles this case with default header values.

Not Found
*/
type GetAddressSuggestionsUsingGETNotFound struct {
}

func (o *GetAddressSuggestionsUsingGETNotFound) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addressSuggestions/][%d] getAddressSuggestionsUsingGETNotFound ", 404)
}

func (o *GetAddressSuggestionsUsingGETNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAddressSuggestionsUsingGETInternalServerError creates a GetAddressSuggestionsUsingGETInternalServerError with default headers values
func NewGetAddressSuggestionsUsingGETInternalServerError() *GetAddressSuggestionsUsingGETInternalServerError {
	return &GetAddressSuggestionsUsingGETInternalServerError{}
}

/*GetAddressSuggestionsUsingGETInternalServerError handles this case with default header values.

Internal Server Error.
*/
type GetAddressSuggestionsUsingGETInternalServerError struct {
	Payload *models.ProblemDetails
}

func (o *GetAddressSuggestionsUsingGETInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/addressLookup/v2/addressSuggestions/][%d] getAddressSuggestionsUsingGETInternalServerError  %+v", 500, o.Payload)
}

func (o *GetAddressSuggestionsUsingGETInternalServerError) GetPayload() *models.ProblemDetails {
	return o.Payload
}

func (o *GetAddressSuggestionsUsingGETInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProblemDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
